import{reviewedLua}from'../../contracts/capture.ts';
import{test,expect}from'@playwright/test';import{readFileSync}from'node:fs';
const g=JSON.parse(readFileSync('experiments/EXP-026-four-radio/declarations.json','utf8')),deploymentId='a'.repeat(64),endpointId=g.links[0].id+':endpoint:1';
async function open(page:any,lua=false){await page.route('**/api/observation/config',(r:any)=>r.fulfill({json:{graph:g,deploymentId}}));await page.route('**/api/capture/config',(r:any)=>r.fulfill({json:{deploymentId,endpoints:[endpointId],luaProfiles:lua?[reviewedLua]:[]}}));await page.goto('/');await page.getByLabel('Approved lab',{exact:true}).selectOption(g.provenance.bundleId);await page.getByRole('button',{name:'Open recorded topology',exact:true}).click();await page.getByRole('button',{name:'Connect enrolled runtime'}).click();await page.getByRole('button',{name:'Inspect switch1 ethernet-1/1',exact:true}).click();await page.getByRole('button',{name:'Capture & TShark',exact:true}).click();await page.getByLabel('Capture endpoint',{exact:true}).selectOption('1');await page.getByLabel('PCAP storage filename',{exact:true}).fill('trial.pcap');}
function result(x:any){return{contract:'capture/0.1',id:x.jobId,deploymentId,endpointId,filename:x.filename,sha256:'c'.repeat(64),bytes:128,createdAt:new Date().toISOString(),expiresAt:new Date(Date.now()+300000).toISOString(),limited:true,packets:[{number:1,seconds:'0.0',bytes:64,source:'192.0.2.1',destination:'192.0.2.2',protocol:'<script>bad</script>'}],analysis:'complete',completeness:'not_established'};}
test('qualified exact endpoint capture produces safe metadata and managed download; Lua stays gated',async({page})=>{
 let sent:any;await page.route('**/api/capture',r=>{sent=r.request().postDataJSON();return r.fulfill({json:{capture:result(sent)}});});await open(page);await page.getByLabel('Capture filter (BPF)',{exact:true}).fill('icmp');await page.getByLabel('TShark display filter',{exact:true}).fill('icmp');await page.getByRole('button',{name:'Start capture',exact:true}).click();await expect(page.getByLabel('Capture result')).toContainText('Byte limit reached');expect(sent.endpointId).toBe(endpointId);expect(sent.captureFilter).toBe('icmp');await expect(page.getByRole('link',{name:'Download trial.pcap'})).toHaveAttribute('href',`/api/capture/${sent.jobId}/download`);await expect(page.getByRole('cell',{name:'<script>bad</script>',exact:true})).toBeVisible();await page.getByLabel('Include Lua settings').check();await expect(page.getByRole('button',{name:'Start capture',exact:true})).toBeDisabled();await page.screenshot({path:'test-results/capture-operational.png',fullPage:true});await page.setViewportSize({width:390,height:844});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBeTruthy();
});
test('cancel is scoped to job and stale capture response cannot return artifact',async({page})=>{
 let sent:any,cancel:any;await page.route('**/api/capture',async r=>{sent=r.request().postDataJSON();await new Promise(resolve=>setTimeout(resolve,600));await r.fulfill({json:{capture:result(sent)}}).catch(()=>{});});await page.route('**/api/capture/cancel',r=>{cancel=r.request().postDataJSON();return r.fulfill({json:{cancelled:true}});});await open(page);await page.getByRole('button',{name:'Start capture',exact:true}).click();await page.getByRole('button',{name:'Cancel capture'}).click();await page.waitForTimeout(700);expect(cancel.jobId).toBe(sent.jobId);await expect(page.getByRole('link',{name:'Download trial.pcap'})).toHaveCount(0);await expect(page.getByText('Capture cancelled; no artifact retained.')).toBeVisible();
});

test('reviewed Lua ID, hash provenance and filter are explicit; unknown scripts and arguments stay disabled',async({page})=>{
 let sent:any;await page.route('**/api/capture',r=>{sent=r.request().postDataJSON();return r.fulfill({json:{capture:{...result(sent),lua:{id:reviewedLua.id,sha256:reviewedLua.sha256}}}});});
 await open(page,true);await page.getByLabel('Include Lua settings').check();await page.getByLabel('Lua script reference').fill('../unreviewed.lua');await expect(page.getByRole('button',{name:'Start capture',exact:true})).toBeDisabled();await page.getByLabel('Lua script reference').fill(reviewedLua.id);await page.getByLabel('Lua script arguments').fill('unsafe');await expect(page.getByRole('button',{name:'Start capture',exact:true})).toBeDisabled();await page.getByLabel('Lua script arguments').fill('');await page.getByLabel('TShark display filter',{exact:true}).fill('clabprobe.sequence == 7');await page.getByRole('button',{name:'Start capture',exact:true}).click();await expect(page.getByLabel('Capture result')).toContainText(reviewedLua.sha256);expect(sent.luaId).toBe(reviewedLua.id);expect(sent.displayFilter).toBe('clabprobe.sequence == 7');expect(sent.luaArgs).toBeUndefined();
});
