import{test,expect}from'@playwright/test';import{readFile}from'node:fs/promises';import{createHash}from'node:crypto';
test('actual enrolled Linux capture and managed download',async({page})=>{
 test.skip(process.env.CLAB_CAPTURE_LIVE!=='1','Explicit fresh-session runtime trial only');
 await page.goto('/');await page.getByLabel('Approved lab',{exact:true}).selectOption('RUNTIME-PAIR');await page.getByRole('button',{name:'Load native declarations',exact:true}).click();await expect(page.locator('.wb-status')).toContainText('Native declarations loaded',{timeout:20000});await page.getByRole('button',{name:'Connect enrolled runtime'}).click();await page.getByRole('button',{name:'Inspect left eth1',exact:true}).click();await page.getByRole('button',{name:'Capture & TShark',exact:true}).click();await page.getByLabel('Capture endpoint',{exact:true}).selectOption('0');await page.getByLabel('PCAP storage filename',{exact:true}).fill('live.pcap');await page.getByLabel('Duration (seconds)',{exact:true}).fill('2');await page.getByLabel('Capture filter (BPF)',{exact:true}).fill('icmp');await page.getByLabel('TShark display filter',{exact:true}).fill('icmp');await page.getByRole('button',{name:'Start capture',exact:true}).click();await expect(page.getByRole('link',{name:'Download live.pcap'})).toBeVisible({timeout:40000});await expect(page.getByLabel('Capture result')).toContainText('Complete within first-100-frame limit');const download=page.waitForEvent('download');await page.getByRole('link',{name:'Download live.pcap'}).click();const d=await download;expect(d.suggestedFilename()).toBe('live.pcap');const bytes=await readFile((await d.path())!);expect(bytes.length).toBeGreaterThanOrEqual(24);expect(bytes.length).toBeLessThanOrEqual(1048576);await expect(page.getByLabel('Capture result')).toContainText(createHash('sha256').update(bytes).digest('hex'));
});

test('actual reviewed Lua filter and script provenance',async({page})=>{
 test.skip(process.env.CLAB_LUA_LIVE!=='1','Explicit qualified fresh-session Lua trial only');
 await page.goto('/');await page.getByLabel('Approved lab',{exact:true}).selectOption('RUNTIME-PAIR');await page.getByRole('button',{name:'Load native declarations',exact:true}).click();await expect(page.locator('.wb-status')).toContainText('Native declarations loaded',{timeout:20000});await page.getByRole('button',{name:'Connect enrolled runtime'}).click();await page.getByRole('button',{name:'Inspect left eth1',exact:true}).click();await page.getByRole('button',{name:'Capture & TShark',exact:true}).click();await page.getByLabel('Capture endpoint',{exact:true}).selectOption('0');await page.getByLabel('PCAP storage filename',{exact:true}).fill('lua-live.pcap');await page.getByLabel('Duration (seconds)',{exact:true}).fill('2');await page.getByLabel('Include Lua settings').check();await page.getByLabel('Lua script reference').fill('clab-probe-v1');await page.getByLabel('TShark display filter',{exact:true}).fill('clabprobe.sequence == 7');await page.getByRole('button',{name:'Start capture',exact:true}).click();await expect(page.getByRole('link',{name:'Download lua-live.pcap'})).toBeVisible({timeout:40000});await expect(page.getByLabel('Capture result')).toContainText('Complete within first-100-frame limit');await expect(page.getByLabel('Capture result')).toContainText('Reviewed Lua: clab-probe-v1');if(process.env.CLAB_REANALYSIS_LIVE==='1'){const href=await page.getByRole('link',{name:'Download lua-live.pcap'}).getAttribute('href');await page.getByLabel('TShark display filter',{exact:true}).fill('clabprobe.sequence == 99');await page.getByRole('button',{name:'Reanalyze current PCAP',exact:true}).click();await expect(page.getByText('Reanalysis complete. No new capture; original expiry unchanged.')).toBeVisible({timeout:25000});await expect(page.getByRole('link',{name:'Download lua-live.pcap'})).toHaveAttribute('href',href!);await expect(page.getByLabel('Capture result')).toContainText('Displayed filter: clabprobe.sequence == 99');}
});
