import{test,expect}from'@playwright/test';import{execFileSync}from'node:child_process';import{readFileSync,writeFileSync,mkdirSync}from'node:fs';
test('maximum-size GUI retains historical evidence on actual injected collection failures',async({page})=>{
 test.setTimeout(90000);test.skip(process.env.CLAB_CAPACITY_FAULTS!=='1','Explicit fresh maximum trial and process faults only');const s=JSON.parse(readFileSync(process.env.CLAB_OBSERVATION_SESSION!,'utf8'));expect(s.profile).toBe('CAPACITY-MAX');const dir=(process.env.CLAB_CAPACITY_EVIDENCE_DIR??'experiments/EXP-024-consolidation')+'/browser-faults-'+Date.now();mkdirSync(dir);const evidence:any[]=[];
 const guest=(...a:string[])=>execFileSync('limactl',['shell',s.vm,'sudo',...a],{timeout:20000,encoding:'utf8',stdio:'pipe'});const mode=(v:string)=>guest('python3','-c','import json;json.dump({"mode":'+JSON.stringify(v)+'},open("/run/exp024-fault.json","w"))');const sha=guest('sha256sum','/usr/local/bin/containerlab').split(' ')[0];expect(sha).toBe(s.nativeBinarySha256);
 execFileSync('limactl',['copy','experiments/EXP-024-consolidation/fault_cli.py',s.vm+':/tmp/exp024-fault-cli.py']);guest('mv','/usr/local/bin/containerlab','/usr/local/bin/containerlab-exp024-original');
 try{
  guest('install','-m','755','/tmp/exp024-fault-cli.py','/usr/local/bin/containerlab');mode('none');await page.goto('/');await page.getByRole('button',{name:'Runtime observations',exact:true}).click();const refresh=page.getByRole('button',{name:'Refresh runtime',exact:true}),snapshot=page.getByRole('region',{name:'Runtime snapshot'}),inspector=page.getByRole('region',{name:'Observed endpoints'});await refresh.click();await expect(page.getByRole('status')).toContainText('Fresh');
  await page.getByRole('button',{name:'Link 16 · veth',exact:false}).click();mode('exit');await page.waitForTimeout(1100);await refresh.click();await expect(inspector).toContainText('INTERFACE_INSPECTION_UNAVAILABLE');await expect(inspector).toContainText('MATCHED_ENROLLED_ATTRIBUTES');await expect(page.getByRole('button',{name:'Link 16 · veth',exact:false})).toHaveAttribute('aria-pressed','true');evidence.push({stage:'one-node-failure',remainingPeerVisible:true});
  const last=await snapshot.getByText(/^Last observed:/).textContent();
  for(const [fault,message] of [['timeout','timed out'],['oversize','output limit']]){mode(fault);await page.waitForTimeout(1100);await refresh.click();await expect(page.getByRole('status')).toContainText(message,{timeout:12000});await expect(snapshot).toContainText('last successful observation; current state unavailable');await expect(inspector).toContainText('Stale or last-known evidence');expect((await snapshot.getByText(/^Last observed:/).textContent())?.split(' · ')[0]).toBe(last?.split(' · ')[0]);evidence.push({stage:fault,lastTimestampPreserved:true});}
  mode('none');await page.waitForTimeout(1100);await refresh.click();await expect(page.getByRole('status')).toContainText('Fresh');await expect(inspector).not.toContainText('INTERFACE_INSPECTION_UNAVAILABLE');await page.screenshot({path:dir+'/recovered.png',fullPage:true});evidence.push({stage:'recovery',fresh:true});
 }finally{guest('mv','/usr/local/bin/containerlab-exp024-original','/usr/local/bin/containerlab');guest('rm','-f','/run/exp024-fault.json');expect(guest('sha256sum','/usr/local/bin/containerlab').split(' ')[0]).toBe(sha);writeFileSync(dir+'/results.json',JSON.stringify(evidence,null,2)+'\n');}
});
