import{test,expect}from'@playwright/test';import{readFileSync,writeFileSync,mkdirSync}from'node:fs';
test('consolidated live refresh samples preserve occurrence selection and responsiveness',async({page})=>{
 test.setTimeout(180000);test.skip(!process.env.CLAB_CONSOLIDATION_TRIAL,'Explicit capacity qualification only');const s=JSON.parse(readFileSync(process.env.CLAB_OBSERVATION_SESSION!,'utf8')),e=JSON.parse(readFileSync('experiments/EXP-024-consolidation/expectations.json','utf8')).find((e:any)=>e.profile===s.profile);expect(e).toBeTruthy();const dir=(process.env.CLAB_CAPACITY_EVIDENCE_DIR??'experiments/EXP-024-consolidation')+'/browser-'+s.profile+'-'+Date.now();mkdirSync(dir);const samples:any[]=[];
 await page.goto('/?view=evidence');await page.getByRole('button',{name:'Runtime observations',exact:true}).click();const refresh=page.getByRole('button',{name:'Refresh runtime',exact:true}),snapshot=page.getByRole('region',{name:'Runtime snapshot'}),inspector=page.getByRole('region',{name:'Observed endpoints'});
 await page.evaluate(()=>{const w=window as any;w.capacityGaps=[];w.capacityLast=performance.now();w.capacityTimer=setInterval(()=>{const now=performance.now();w.capacityGaps.push(now-w.capacityLast);w.capacityLast=now;},16);});
 async function once(){const started=performance.now();const response=page.waitForResponse(r=>r.url().endsWith('/api/observation/snapshot'));await refresh.click();const x=await (await response).json();expect(x.snapshot).toBeTruthy();await expect(snapshot).toContainText(x.snapshot.observedAt);await expect(refresh).toBeEnabled();return {refreshMs:performance.now()-started,sequence:x.snapshot.sequence};}
 let warmup:any;
 try{warmup=await once();for(let i=0;i<10;i++){const link=e.links[i%2?e.links.length-1:0],button=page.getByRole('button',{name:`Link ${link.occurrence+1} · veth`,exact:false});await button.focus();await page.keyboard.press('Enter');await page.waitForTimeout(1100);samples.push(await once());await expect(button).toHaveAttribute('aria-pressed','true');for(const endpoint of link.endpoints){await expect(inspector).toContainText(endpoint.node+':'+endpoint.declared);await expect(inspector).toContainText(endpoint.native);}await expect(inspector.getByText('Endpoint occurrence',{exact:true})).toHaveCount(2);}
 if(e.nodes.some((n:any)=>n.name==='isolated')){await page.getByRole('button',{name:'isolated linux',exact:true}).click();await expect(inspector).toContainText('Container isolated: running');await expect(inspector).toContainText('No declared data-plane endpoints.');}await page.setViewportSize({width:390,height:844});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBeTruthy();await page.screenshot({path:dir+'/narrow.png',fullPage:true});
 const gaps=await page.evaluate(()=>{const w=window as any;clearInterval(w.capacityTimer);return w.capacityGaps as number[];});const sorted=samples.map(x=>x.refreshMs).sort((a,b)=>a-b);expect(Math.max(...gaps)).toBeLessThanOrEqual(250);expect(sorted[9]).toBeLessThan(12000);expect(sorted[Math.ceil(.95*sorted.length)-1]).toBeLessThanOrEqual(5000);writeFileSync(dir+'/browser.json',JSON.stringify({profile:s.profile,warmup,samples,maxMainThreadIntervalMs:Math.max(...gaps),intervalSamples:gaps.length},null,2)+'\n');
 }finally{writeFileSync(dir+'/attempt.json',JSON.stringify({profile:s.profile,warmup,samples},null,2)+'\n');}
});

test('incompatible session explains fresh enrollment and recorded views remain available (mock)',async({page})=>{
 await page.route('**/api/observation/config',r=>r.fulfill({status:422,json:{code:'INCOMPATIBLE_SESSION'}}));await page.goto('/?view=evidence');await page.getByRole('button',{name:'Runtime observations',exact:true}).click();await expect(page.getByRole('status')).toContainText('requires fresh enrollment');await expect(page.getByRole('button',{name:'Refresh runtime',exact:true})).toBeDisabled();await expect(page.getByRole('region',{name:'Runtime snapshot'})).toHaveCount(0);const recorded=page.getByRole('combobox',{name:'Recorded native fixture',exact:true});await expect(recorded).toBeEnabled();await recorded.selectOption({label:'Native F1 · partial'});await expect(page.getByRole('region',{name:'Runtime observation',exact:true})).toHaveCount(0);await expect(page.getByRole('heading',{name:'Native F1',exact:true})).toBeVisible();await expect(page.getByRole('region',{name:'Accessible object list'}).getByRole('button',{name:/^Link /})).toHaveCount(3);
});
