import{test,expect}from'@playwright/test';import{readFileSync}from'node:fs';import{associateMulti}from'../../contracts/legacy/multi-observation.ts';
const read=(p:string)=>JSON.parse(readFileSync('experiments/EXP-026-four-radio/'+p,'utf8')),g=read('declarations.json'),s=read('session.json'),raw=read('native-observation.json'),expected=read('expectations.json');
test('four-radio actual declaration, inventory and explicitly enrolled runtime',async({page})=>{
 test.skip(!process.env.CLAB_FOUR_RADIO_TRIAL,'Requires explicit fresh four-radio trial');test.setTimeout(60000);
 await page.goto('/?view=evidence');await page.getByRole('button',{name:'On-demand native loading',exact:true}).click();await page.getByLabel('Approved bundle').selectOption('FOUR-RADIO-SDR');await expect(page.getByRole('region',{name:'Approved companion inventory'})).toContainText('radio1.json');await page.getByRole('button',{name:'Load native declarations',exact:true}).click();await expect(page.getByRole('status')).toContainText('completed');await expect(page.getByText('8 nodes / 7 link occurrences')).toBeVisible();
 for(const n of expected.nodes)await expect(page.getByRole('button',{name:n.name+' '+n.kind,exact:true})).toBeVisible();
 await page.getByRole('button',{name:'Runtime observations',exact:true}).click();const refresh=page.getByRole('button',{name:'Refresh runtime',exact:true});await refresh.click();await expect(page.getByRole('region',{name:'Runtime snapshot'})).toContainText('observation/0.8');await expect(page.getByRole('region',{name:'Runtime snapshot'})).toContainText('Native lab: four-radio-sdr');const inspector=page.getByRole('region',{name:'Observed endpoints'});
 for(const l of expected.links){const button=page.getByRole('button',{name:`Link ${l.occurrence+1} · veth`,exact:false});await button.focus();await page.keyboard.press('Enter');for(const e of l.endpoints){await expect(inspector).toContainText(e.node+':'+e.declared);await expect(inspector).toContainText(e.native);}await expect(inspector).toContainText('MATCHED_ENROLLED_ATTRIBUTES');}
 await page.waitForTimeout(1100);await refresh.click();await expect(page.getByRole('button',{name:'Link 7 · veth',exact:false})).toHaveAttribute('aria-pressed','true');await expect(page.getByRole('region',{name:'Runtime snapshot'})).toContainText('not assessed');await page.screenshot({path:'test-results/four-radio-live.png',fullPage:true});
});
test('four-radio stale, failure, identity conflict, recovery and cancellation keep selected occurrence (replay/mock)',async({page})=>{
 const data=associateMulti(raw,s.binding,1);let code='',stale=true,delay=false;
 await page.route('**/api/observation/config',r=>r.fulfill({json:{graph:g,deploymentId:s.binding.deploymentId}}));
 await page.route('**/api/observation/snapshot',async r=>{if(delay)await new Promise(resolve=>setTimeout(resolve,700));await r.fulfill(code?{status:422,json:{code}}:{json:{snapshot:{...data,observedAt:new Date(Date.now()-(stale?16000:0)).toISOString()}}}).catch(()=>{});});
 await page.goto('/?view=evidence');await page.getByRole('button',{name:'Runtime observations',exact:true}).click();const refresh=page.getByRole('button',{name:'Refresh runtime',exact:true});await refresh.click();await expect(page.getByRole('status')).toContainText('Stale');const link=page.getByRole('button',{name:'Link 6 · veth',exact:false});await link.click();
 for(const c of ['INSPECTION_FAILED','ASSOCIATION_CONFLICT']){code=c;await refresh.click();await expect(page.getByRole('status')).toContainText(c==='INSPECTION_FAILED'?'Absence is not established':'Replacement resources were not associated');await expect(link).toHaveAttribute('aria-pressed','true');}
 code='';stale=false;await refresh.click();await expect(page.getByRole('status')).toContainText('Fresh');delay=true;await refresh.click();await page.getByRole('button',{name:'Cancel inspection',exact:true}).click();await expect(page.getByRole('status')).toContainText('cancelled');await page.waitForTimeout(800);await expect(link).toHaveAttribute('aria-pressed','true');delay=false;await refresh.click();await expect(page.getByRole('status')).toContainText('Fresh');
});
