import{test,expect}from'@playwright/test';import{readFileSync,writeFileSync,mkdirSync}from'node:fs';import{readFile}from'node:fs/promises';import{execFileSync,spawn}from'node:child_process';import{createHash}from'node:crypto';
test('supported Phase5 workflow: declarations, observations, per-node logs, capture/reanalysis, disconnect and recovery',async({page})=>{
 test.skip(process.env.CLAB_INTEGRATED_LIVE!=='1','Explicit fresh-session integrated qualification only');test.setTimeout(180000);
 const exp='experiments/EXP-034-integrated-gui',dir=readFileSync(exp+'/session-path.txt','utf8').trim(),file=dir+'/observation-session.json';expect(process.env.CLAB_OBSERVATION_SESSION).toBe(file);
 const original=readFileSync(file,'utf8'),session=JSON.parse(original),vm=session.vm;expect(session.profile).toBe('RUNTIME-PAIR');const out=exp+'/attempt-'+Date.now();mkdirSync(out);const evidence:any={vm,checks:[],browserErrors:[]};let traffic:ReturnType<typeof spawn>|undefined;
 page.on('pageerror',e=>evidence.browserErrors.push(e.message));
 const guest=(...a:string[])=>execFileSync('limactl',['shell',vm,...a],{encoding:'utf8',timeout:20000});
 const pass=(name:string)=>{evidence.checks.push(name);writeFileSync(out+'/RESULTS.json',JSON.stringify(evidence,null,2));};
 async function link(){await page.getByRole('button',{name:'Inspect left eth1',exact:true}).click();await page.getByRole('button',{name:'Capture & TShark',exact:true}).click();await page.getByLabel('Capture endpoint',{exact:true}).selectOption('0');await page.getByLabel('PCAP storage filename',{exact:true}).fill('integrated.pcap');}
 async function download(){const wait=page.waitForEvent('download');await page.getByRole('link',{name:'Download integrated.pcap'}).click();return readFile((await(await wait).path())!);}
 try{
  await page.goto('/');await page.getByLabel('Approved lab',{exact:true}).selectOption('RUNTIME-PAIR');const loadResponse=page.waitForResponse(r=>r.url().endsWith('/api/native/load'));await page.getByRole('button',{name:'Load native declarations',exact:true}).click();const loaded=await(await loadResponse).json();expect(loaded.graph.nodes.map((n:any)=>n.name).sort()).toEqual(['left','right']);expect(loaded.graph.links).toHaveLength(1);await expect(page.locator('.wb-view-tabs')).toContainText('EXECUTED NATIVE LOAD');await page.getByRole('button',{name:'Connect enrolled runtime'}).click();await page.getByRole('button',{name:'Refresh',exact:true}).click();await expect(page.locator('.wb-runtime-bar')).toContainText('Runtime observed');expect(await page.locator('.wb-device').filter({hasText:'running'}).count()).toBe(2);pass('actual native declarations, exact enrollment and observed running nodes');
  await page.getByRole('button',{name:'Select left',exact:true}).click();await page.getByRole('button',{name:'Logs',exact:true}).click();await page.getByRole('button',{name:'Load logs',exact:true}).click();await expect(page.getByLabel('Node log output')).toContainText('EXP034_LEFT');await expect(page.getByLabel('Node log output')).toContainText('<script>EXP034_LITERAL</script>');expect(await page.locator('script').filter({hasText:'EXP034_LITERAL'}).count()).toBe(0);
  await page.getByLabel('Follow logs',{exact:true}).check();const left=session.binding.nodes.find((n:any)=>n.node==='left');guest('sudo','docker','exec',left.id,'sh','-c',"printf 'EXP034_FOLLOW\\n' > /proc/1/fd/1");await expect(page.getByLabel('Node log output')).toContainText('EXP034_FOLLOW',{timeout:12000});await page.getByRole('button',{name:'Stop logs',exact:true}).click();await expect(page.getByLabel('Follow logs',{exact:true})).not.toBeChecked();
  await page.getByRole('button',{name:'Select right',exact:true}).click();await expect(page.getByLabel('Node log output')).not.toContainText('EXP034_LEFT');await page.getByRole('button',{name:'Load logs',exact:true}).click();await expect(page.getByLabel('Node log output')).toContainText('EXP034_RIGHT');await expect(page.getByLabel('Node log output')).not.toContainText('EXP034_FOLLOW');pass('per-node log identity, literal hostile text, follow/stop and selection reset');
  const pid=guest('sudo','docker','inspect','--format','{{.State.Pid}}',left.id).trim();expect(pid).toMatch(/^[0-9]+$/);const send='import socket,time;s=socket.socket(socket.AF_INET,socket.SOCK_DGRAM);[(s.sendto(b"CLAB\\x01\\x00\\x07",("192.0.2.2",49321)),s.sendto(b"CLAB\\x01\\x00\\x08",("192.0.2.2",49321)),time.sleep(.1)) for _ in range(500)]';traffic=spawn('limactl',['shell',vm,'sudo','nsenter','-t',pid,'-n','python3','-c',send],{stdio:'ignore'});
  await link();await page.getByLabel('Duration (seconds)',{exact:true}).fill('2');await page.getByLabel('Capture filter (BPF)',{exact:true}).fill('udp port 49321');await page.getByLabel('Include Lua settings').check();await page.getByLabel('Lua script reference').fill('clab-probe-v1');await page.getByLabel('TShark display filter',{exact:true}).fill('clabprobe.sequence == 7');
  const captured=page.waitForResponse(r=>r.url().endsWith('/api/capture')&&r.request().method()==='POST');await page.getByRole('button',{name:'Start capture',exact:true}).click();const first=(await(await captured).json()).capture;expect(first.analysis).toBe('complete');expect(first.packets.length).toBeGreaterThan(0);await expect(page.getByLabel('Capture result')).toContainText('CLABPROBE');const before=await download();expect(createHash('sha256').update(before).digest('hex')).toBe(first.sha256);
  await page.getByLabel('TShark display filter',{exact:true}).fill('clabprobe.sequence == 8');const analyzed=page.waitForResponse(r=>r.url().endsWith('/api/capture/reanalyze'));await page.getByRole('button',{name:'Reanalyze current PCAP',exact:true}).click();const second=(await(await analyzed).json()).analysis;expect(second.analysis).toBe('complete');expect(second.packets.length).toBeGreaterThan(0);expect(second.packets.every((p:any)=>!first.packets.some((q:any)=>q.number===p.number))).toBe(true);expect(second.sha256).toBe(first.sha256);expect(second.expiresAt).toBe(first.expiresAt);expect(second.capturedAt).toBe(first.createdAt);expect(await download()).toEqual(before);evidence.capture={sha256:first.sha256,bytes:first.bytes,firstFrames:first.packets.map((p:any)=>p.number),secondFrames:second.packets.map((p:any)=>p.number),expiryUnchanged:true};pass('actual capture → reviewed filter → disjoint reanalysis → identical downloaded bytes and expiry');
  await page.getByLabel('TShark display filter',{exact:true}).fill('invalid display syntax !');await page.getByRole('button',{name:'Reanalyze current PCAP',exact:true}).click();await expect(page.getByText('Analysis unavailable. The valid original PCAP remains downloadable until expiry.')).toBeVisible();expect(await download()).toEqual(before);pass('invalid filter distinct from zero matches, original PCAP retained');
  writeFileSync(file,JSON.stringify({...session,reanalysisCapability:undefined}));await page.getByRole('button',{name:'Reanalyze current PCAP',exact:true}).click();await expect(page.getByText('Reanalysis is not qualified for this session.')).toBeVisible();const refused=await page.request.get(`/api/capture/${first.id}/download`);expect(refused.status()).toBe(422);await page.getByRole('button',{name:'Disconnect runtime'}).click();await expect(page.getByRole('button',{name:'Refresh',exact:true})).toBeDisabled();writeFileSync(file,original);expect((await page.request.get(`/api/capture/${first.id}/download`)).status()).toBe(422);await page.getByRole('button',{name:'Connect enrolled runtime'}).click();pass('observed capability withdrawal refuses analysis/download; explicit disconnect/reconnect cannot resurrect evicted artifact');
  await link();await page.getByLabel('Duration (seconds)',{exact:true}).fill('4');await page.getByLabel('TShark display filter',{exact:true}).fill('');await page.getByLabel('Include Lua settings').uncheck();const started=page.waitForRequest(r=>r.url().endsWith('/api/capture')&&r.method()==='POST');await page.getByRole('button',{name:'Start capture',exact:true}).click();await started;await page.getByRole('button',{name:'Disconnect runtime'}).click();await page.waitForTimeout(8500);await expect(page.getByLabel('Capture result')).toHaveCount(0);await expect(page.getByRole('button',{name:'Refresh',exact:true})).toBeDisabled();await page.getByRole('button',{name:'Connect enrolled runtime'}).click();await link();await page.getByLabel('Duration (seconds)',{exact:true}).fill('1');await page.getByRole('button',{name:'Start capture',exact:true}).click();await expect(page.getByRole('link',{name:'Download integrated.pcap'})).toBeVisible({timeout:25000});pass('disconnect cancels pending capture, rejects late output, reconnect permits new capture');
  await page.screenshot({path:out+'/integrated-desktop.png',fullPage:true});await page.setViewportSize({width:390,height:844});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await page.screenshot({path:out+'/integrated-mobile.png',fullPage:true});await page.getByRole('button',{name:'Select left',exact:true}).click();await page.getByRole('button',{name:'Logs',exact:true}).click();await expect(page.getByLabel('Node log output')).not.toContainText('EXP034_RIGHT');await expect(page.getByLabel('Capture result')).toHaveCount(0);expect(evidence.browserErrors).toEqual([]);pass('navigation clears prior evidence; mobile width and browser exception checks');evidence.outcome='PASS';
 }catch(e){evidence.outcome='FAIL';evidence.reason=e instanceof Error?e.message:String(e);await page.screenshot({path:out+'/failure.png',fullPage:true}).catch(()=>{});throw e;}finally{writeFileSync(file,original);if(traffic?.exitCode===null)await new Promise<void>(resolve=>traffic!.once('close',()=>resolve()));writeFileSync(out+'/RESULTS.json',JSON.stringify(evidence,null,2));}
});
