import {test,expect}from'@playwright/test';import{readFileSync}from'node:fs';import{execFileSync}from'node:child_process';
test('actual endpoint inspector follows native operational down/up without claiming link health',async({page})=>{
 test.skip(!process.env.CLAB_OBSERVATION_SESSION,'Explicit fresh interface trial required');const s=JSON.parse(readFileSync(process.env.CLAB_OBSERVATION_SESSION!,'utf8'));test.skip(s.profile==='SRL-PAIR','SRL has separate profile qualification');test.skip(!s.binding.nodes[0].endpoint,'Interface enrollment required');
 const guest=(...a:string[])=>execFileSync('limactl',['shell',s.vm,'sudo',...a],{timeout:20000,stdio:'pipe'}).toString();const id=s.binding.nodes.find((n:any)=>n.node==='left').id;const pid=guest('docker','inspect','--format','{{.State.Pid}}',id).trim();
 await page.goto('/');await page.getByRole('button',{name:'Runtime observations',exact:true}).click();const refresh=page.getByRole('button',{name:'Refresh runtime',exact:true});await refresh.click();await page.getByRole('button',{name:'Link 1 · veth',exact:false}).click();const endpoints=page.getByRole('region',{name:'Observed endpoints'});await expect(endpoints).toContainText('left:eth1');await expect(endpoints).toContainText('right:eth1');await expect(endpoints).toContainText('MATCHED_ENROLLED_ATTRIBUTES');
 try{guest('nsenter','-t',pid,'-n','ip','link','set','eth1','down');await page.waitForTimeout(1100);await refresh.click();await expect(endpoints.locator('dt:has-text("Operational state") + dd').first()).toHaveText('down');await expect(endpoints.locator('dt:has-text("Administrative state") + dd').first()).toHaveText('down');await expect(endpoints).toContainText('Peer identityunknown');await expect(endpoints).toContainText('linux_netlink_flags');await expect(page.getByRole('button',{name:'Link 1 · veth',exact:false})).toHaveAttribute('aria-pressed','true');}
 finally{guest('nsenter','-t',pid,'-n','ip','link','set','eth1','up');}
 await page.waitForTimeout(1100);await refresh.click();await expect(refresh).toBeEnabled();await expect(endpoints.locator('dt:has-text("Operational state") + dd').first()).toHaveText('up');await expect(endpoints.locator('dt:has-text("Administrative state") + dd').first()).toHaveText('up');await page.screenshot({path:'test-results/interfaces-live.png',fullPage:true});await page.setViewportSize({width:390,height:844});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBeTruthy();
});
test('endpoint absence and unresolved replacements retain declared links (transport mock)',async({page})=>{
 const graph=JSON.parse(readFileSync('experiments/EXP-018-runtime-observation/qualified-session.json','utf8')).graph;let stage='absent',sequence=0;
 await page.route('**/api/observation/config',r=>r.fulfill({json:{graph,deploymentId:'d'.repeat(64)}}));
 await page.route('**/api/observation/snapshot',r=>r.fulfill({json:{snapshot:{contract:'observation/0.2',deploymentId:'d'.repeat(64),sourceSha256:graph.provenance.sourceSha256,nativeCommit:'5ae50094a3afd70e4e1674fe5385e64d8979da26',sequence:++sequence,observedAt:new Date(Date.now()-16000).toISOString(),freshForMs:15000,linkHealth:'unknown',nodes:['left','right'].map((node,i)=>({node,containerId:(i?'b':'a').repeat(64),state:'running',association:'enrolled_full_id'})),endpoints:['left','right'].map((node,i)=>({node,containerId:(i?'b':'a').repeat(64),declaredInterface:'eth1',status:stage,reason:stage==='absent'?'MISSING_FROM_NATIVE_INVENTORY':'IDENTITY_CHANGED',namespaceFingerprint:(i?'e':'f').repeat(64),index:null,mac:null,operationalState:'unknown',administrativeState:'unknown',carrier:'unknown',peer:'unknown',continuity:'unknown'}))}}}));
 await page.goto('/');await page.getByRole('button',{name:'Runtime observations',exact:true}).click();const link=page.getByRole('button',{name:'Link 1 · veth',exact:false});await link.click();const refresh=page.getByRole('button',{name:'Refresh runtime',exact:true});await refresh.click();const endpoints=page.getByRole('region',{name:'Observed endpoints'});await expect(endpoints).toContainText('absent · MISSING_FROM_NATIVE_INVENTORY');await expect(endpoints).toContainText('Stale or last-known evidence');await expect(link).toHaveAttribute('aria-pressed','true');stage='unresolved';await refresh.click();await expect(endpoints).toContainText('unresolved · IDENTITY_CHANGED');await expect(link).toHaveAttribute('aria-pressed','true');await expect(endpoints).toContainText('Link health: unknown');
});
