import{test,expect}from'@playwright/test';import{readFileSync}from'node:fs';
const g=JSON.parse(readFileSync('experiments/EXP-026-four-radio/declarations.json','utf8')),deploymentId='a'.repeat(64);
async function open(page:any){await page.route('**/api/observation/config',(r:any)=>r.fulfill({json:{graph:g,deploymentId}}));await page.goto('/');await page.getByLabel('Approved lab',{exact:true}).selectOption(g.provenance.bundleId);await page.getByRole('button',{name:'Open recorded topology',exact:true}).click();await page.getByRole('button',{name:'Connect enrolled runtime'}).click();await page.getByRole('button',{name:'Select radio2',exact:true}).click();await page.getByRole('button',{name:'Logs',exact:true}).click();}
function snapshot(nodeId:string,text:string){return{contract:'node-logs/0.1',deploymentId,nodeId,sourceSha256:g.provenance.sourceSha256,bundleSha256:g.provenance.bundleSha256,observedAt:new Date().toISOString(),text,truncated:true,tailLines:100,source:'container_stdout_stderr'};}
test('tail and literal filter are local, bounded, safe and distinguish no matches from empty source',async({page})=>{
 let calls=0,empty=false;await page.route('**/api/node-logs?*',r=>{calls++;return r.fulfill({json:{snapshot:snapshot(new URL(r.request().url()).searchParams.get('nodeId')!,empty?'':Array.from({length:100},(_,i)=>`line ${i} ${i===99?'[WARN] <script>.*':''}`).join('\n')+'\n')}});});
 await open(page);await page.getByRole('button',{name:'Load logs',exact:true}).click();await expect(page.getByLabel('Node log output')).toContainText('line 0');await page.getByLabel('Display log tail').selectOption('25');await expect(page.getByLabel('Node log output')).not.toContainText('line 0 ');await page.getByLabel('Filter fetched log lines').fill('[warn]');await expect(page.getByLabel('Node log output')).toHaveText('line 99 [WARN] <script>.*');expect(calls).toBe(1);await page.screenshot({path:'test-results/log-workflow-desktop.png',fullPage:true});await page.setViewportSize({width:390,height:844});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBeTruthy();await page.getByLabel('Filter fetched log lines').scrollIntoViewIfNeeded();await page.screenshot({path:'test-results/log-workflow-mobile.png',fullPage:true});await expect(page.getByText('Output truncated at the byte limit.')).toBeVisible();await page.getByLabel('Filter fetched log lines').fill('not there');await expect(page.getByText(/No fetched lines match this filter/)).toBeVisible();empty=true;await page.getByRole('button',{name:'Load logs',exact:true}).click();await expect(page.getByLabel('Selected node logs')).toContainText('Log source returned no output.');await expect(page.getByText(/No fetched lines match this filter/)).toHaveCount(0);
});
test('clear cancels pending follow and refuses late output; unsupported errors stop follow and manual retry recovers',async({page})=>{
 let code='',delay=false,calls=0;await page.route('**/api/node-logs?*',async r=>{calls++;if(delay)await new Promise(resolve=>setTimeout(resolve,700));await r.fulfill(code?{status:422,json:{code}}:{json:{snapshot:snapshot(new URL(r.request().url()).searchParams.get('nodeId')!,'test heartbeat')}}).catch(()=>{});});
 await open(page);delay=true;await page.getByLabel('Follow logs',{exact:true}).check();await expect.poll(()=>calls).toBe(1);await page.getByRole('button',{name:'Clear log output'}).click();await page.waitForTimeout(800);await expect(page.getByLabel('Node log output')).toHaveText('No logs loaded for this node.');await expect(page.getByLabel('Follow logs',{exact:true})).not.toBeChecked();delay=false;code='LOG_SOURCE_UNSUPPORTED';await page.getByLabel('Follow logs',{exact:true}).check();await expect(page.getByText('Container logs are unsupported for this node.')).toBeVisible();await expect(page.getByLabel('Follow logs',{exact:true})).not.toBeChecked();code='';await page.getByRole('button',{name:'Load logs',exact:true}).click();await expect(page.getByLabel('Node log output')).toHaveText('test heartbeat');await page.getByLabel('Filter fetched log lines').fill('heartbeat');await page.getByRole('button',{name:'Overview',exact:true}).click();await page.getByRole('button',{name:'Logs',exact:true}).click();await expect(page.getByLabel('Filter fetched log lines')).toHaveValue('');await expect(page.getByLabel('Node log output')).toHaveText('No logs loaded for this node.');
});
test('expired session removes log binding and requires enrollment reconnect',async({page})=>{
 await page.route('**/api/node-logs?*',r=>r.fulfill({status:422,json:{code:'OBSERVATION_UNAVAILABLE'}}));await open(page);await page.getByRole('button',{name:'Load logs',exact:true}).click();await expect(page.locator('.wb-runtime-bar')).toContainText('Runtime session unavailable or expired');await expect(page.getByRole('button',{name:'Refresh',exact:true})).toBeDisabled();await expect(page.getByLabel('Node log output')).toHaveCount(0);
});
test('timeout rejects even a transport that resolves after abort and stops following',async({page})=>{
 await page.clock.install();
 await page.addInitScript(({g,deploymentId})=>{const original=window.fetch;window.fetch=async(input,init)=>{if(String(input).startsWith('/api/node-logs?')){await new Promise(resolve=>setTimeout(resolve,12000));const nodeId=new URL(String(input),location.origin).searchParams.get('nodeId');return new Response(JSON.stringify({snapshot:{contract:'node-logs/0.1',deploymentId,nodeId,sourceSha256:g.provenance.sourceSha256,bundleSha256:g.provenance.bundleSha256,observedAt:new Date().toISOString(),text:'LATE OUTPUT',truncated:false,tailLines:100,source:'container_stdout_stderr'}}));}return original(input,init);};},{g,deploymentId});
 await open(page);await page.getByLabel('Follow logs',{exact:true}).check();await page.clock.fastForward(12500);await expect(page.getByText('Log read cancelled or timed out.')).toBeVisible();await expect(page.getByLabel('Node log output')).not.toContainText('LATE OUTPUT');await expect(page.getByLabel('Follow logs',{exact:true})).not.toBeChecked();
});
