import{test,expect}from'@playwright/test';import{readFileSync}from'node:fs';
test('actual multiple endpoint occurrences, parallel selection and disconnected state',async({page})=>{
 test.skip(!process.env.CLAB_OBSERVATION_SESSION,'Explicit fresh trial required');const s=JSON.parse(readFileSync(process.env.CLAB_OBSERVATION_SESSION!,'utf8'));test.skip(s.profile!=='MULTI-ENDPOINT-V2','Multi endpoint profile only');
 await page.goto('/?view=evidence');await page.getByRole('button',{name:'Runtime observations',exact:true}).click();const refresh=page.getByRole('button',{name:'Refresh runtime',exact:true}),inspector=page.getByRole('region',{name:'Observed endpoints'});await refresh.click();await expect(page.getByRole('region',{name:'Runtime snapshot'})).toContainText('observation/0.7');await expect(inspector).toContainText('router:ethernet-1/1');await expect(inspector).toContainText('router:ethernet-1/2');
 await page.getByRole('button',{name:'Link 1 · veth',exact:false}).click();await expect(inspector).toContainText('client:eth1');await expect(inspector).not.toContainText('client:eth2');await expect(inspector).toContainText('e1-1');await expect(inspector).toContainText('Endpoint occurrence');
 const second=page.getByRole('button',{name:'Link 2 · veth',exact:false});await second.focus();await page.keyboard.press('Enter');await expect(inspector).toContainText('client:eth2');await expect(inspector).not.toContainText('client:eth1');await expect(inspector).toContainText('e1-2');await page.waitForTimeout(1100);await refresh.click();await expect(second).toHaveAttribute('aria-pressed','true');
 await page.getByRole('button',{name:'isolated linux',exact:true}).click();await expect(inspector).toContainText('Container isolated: running');await expect(inspector).toContainText('No declared data-plane endpoints.');await expect(inspector).not.toContainText('MATCHED_ENROLLED_ATTRIBUTES');await page.setViewportSize({width:390,height:844});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBeTruthy();await page.screenshot({path:'test-results/multi-live.png',fullPage:true});
});

import{fixture}from'../helpers/multi.ts';import{associateMulti}from'../../contracts/legacy/multi-observation.ts';
test('multi occurrence partial failures, hostile text, stale and superseded responses (mock)',async({page})=>{
 const f=fixture();const attack='<img src=x onerror=alert(1)>';f.graph.nodes.find((n:any)=>n.name==='isolated').kind=attack;
 // Use accepted graph/provenance, unsupported declaration stays text; no runtime claim for it.
 const data=associateMulti(f.raw,f.binding,1);data.nodes.find(n=>n.node==='isolated')!.kind=attack;data.nodes.find(n=>n.node==='isolated')!.association='unsupported';
 const failed=data.endpoints[0];Object.assign(failed,{status:'unavailable',reason:'INTERFACE_INSPECTION_UNAVAILABLE',operationalState:'unknown',administrativeState:'unknown',carrier:'unknown',supplementSource:'unavailable',supplementReason:'NOT_ASSOCIATED'});
 let sequence=1,delay=false;await page.route('**/api/observation/config',r=>r.fulfill({json:{graph:f.graph,deploymentId:f.binding.deploymentId}}));await page.route('**/api/observation/snapshot',async r=>{if(delay)await new Promise(resolve=>setTimeout(resolve,1200));await r.fulfill({json:{snapshot:{...data,sequence,observedAt:new Date(Date.now()-16000).toISOString()}}}).catch(()=>{});});
 await page.goto('/?view=evidence');await page.getByRole('button',{name:'Runtime observations',exact:true}).click();const refresh=page.getByRole('button',{name:'Refresh runtime',exact:true});await refresh.click();const e=page.getByRole('region',{name:'Observed endpoints'});await expect(e).toContainText('INTERFACE_INSPECTION_UNAVAILABLE');await expect(e).toContainText('MATCHED_ENROLLED_ATTRIBUTES');await expect(page.getByRole('status')).toContainText('Stale');expect(await page.locator('img').count()).toBe(0);
 await page.getByRole('button',{name:'Link 2 · veth',exact:false}).click();await expect(e).not.toContainText('INTERFACE_INSPECTION_UNAVAILABLE');delay=true;sequence=2;await refresh.click();await page.getByRole('button',{name:'Cancel inspection',exact:true}).click();await page.waitForTimeout(1400);await expect(page.getByRole('status')).toContainText('cancelled');await expect(page.getByRole('button',{name:'Link 2 · veth',exact:false})).toHaveAttribute('aria-pressed','true');
 delay=false;sequence=1;await refresh.click();await expect(e).toContainText('client:eth2');
});
