import{test,expect}from'@playwright/test';import{readFileSync}from'node:fs';import{derivePlan}from'../../contracts/enrollment.ts';import{enroll,associateMulti}from'../../contracts/multi-observation.ts';
const g=JSON.parse(readFileSync('experiments/EXP-026-four-radio/declarations.json','utf8')),raw=JSON.parse(readFileSync('experiments/EXP-026-four-radio/native-observation.json','utf8')),binding=enroll(raw,derivePlan(g),'a'.repeat(64),raw.labName);
async function open(page:any){await page.goto('/');await page.getByLabel('Approved lab',{exact:true}).selectOption('FOUR-RADIO-SDR');await page.getByRole('button',{name:'Open recorded topology',exact:true}).click();await expect(page.getByLabel('Lab topology canvas')).toBeVisible();}
test('lab chooser first; exact handles, synchronized table selection, search and safe offline runtime',async({page})=>{await page.goto('/');await expect(page.getByRole('heading',{name:'Open a topology to explore your lab'})).toBeVisible();await open(page);await expect(page.locator('.wb-device')).toHaveCount(8);await expect(page.locator('.wb-port')).toHaveCount(14);await expect(page.locator('.react-flow__edge')).toHaveCount(7);await page.getByRole('button',{name:'Inspect switch1 ethernet-1/3',exact:true}).click();const inspector=page.getByRole('complementary',{name:'Selected object inspector'});await expect(inspector).toContainText('Link 3');await page.getByRole('button',{name:'Interfaces',exact:true}).click();await expect(inspector).toContainText('radio3');await expect(inspector).toContainText('ethernet-1/3');await page.getByRole('button',{name:'Nodes & links',exact:true}).click();await expect(page.getByRole('table').getByRole('button',{name:'switch1:ethernet-1/3 ↔ radio3:eth1',exact:true})).toHaveAttribute('aria-pressed','true');await page.getByRole('searchbox').fill('radio4');await expect(page.getByRole('table').getByRole('button',{name:'radio4',exact:true})).toBeVisible();await page.getByRole('button',{name:'Connect enrolled runtime'}).click();await expect(page.locator('.wb-runtime-bar')).toContainText('No active');await expect(inspector).toContainText('Link 3');});
test('matched replay overlay refresh/failure/cancel/recovery preserves selection; stale and identity mismatch explicit',async({page})=>{
 let fail='',delay=false,stale=false;await page.route('**/api/observation/config',r=>r.fulfill({json:{graph:g,deploymentId:binding.deploymentId}}));await page.route('**/api/observation/snapshot',async r=>{if(delay)await new Promise(resolve=>setTimeout(resolve,600));const snap=associateMulti(raw,binding,1);if(stale)snap.observedAt=new Date(Date.now()-16000).toISOString();await r.fulfill(fail?{status:422,json:{code:fail}}:{json:{snapshot:snap}}).catch(()=>{});});await open(page);await page.getByRole('button',{name:'Select switch1',exact:true}).click();await page.getByRole('button',{name:'Connect enrolled runtime'}).click();await page.getByRole('button',{name:'Refresh',exact:true}).click();await expect(page.locator('.wb-runtime-bar')).toContainText('Runtime observed');await expect(page.locator('.wb-device.chosen')).toContainText('running');const position=await page.locator('.wb-device.chosen').locator('..').getAttribute('style');fail='INSPECTION_FAILED';await page.getByRole('button',{name:'Refresh',exact:true}).click();await expect(page.locator('.wb-runtime-bar')).toContainText('Refresh failed');await expect(page.locator('.wb-device.chosen')).toContainText('last-known');fail='';stale=true;await page.getByRole('button',{name:'Refresh',exact:true}).click(); // older replies are correctly ignored
 delay=true;await page.getByRole('button',{name:'Refresh',exact:true}).click();await page.getByRole('button',{name:'Cancel inspection'}).click();await expect(page.locator('.wb-runtime-bar')).toContainText('cancelled');await page.waitForTimeout(700);delay=false;stale=false;await page.getByRole('button',{name:'Refresh',exact:true}).click();await expect(page.locator('.wb-runtime-bar')).toContainText('Runtime observed');expect(await page.locator('.wb-device.chosen').locator('..').getAttribute('style')).toBe(position);
 await page.route('**/api/observation/config',r=>r.fulfill({json:{graph:{...g,provenance:{...g.provenance,bundleSha256:'b'.repeat(64)}},deploymentId:binding.deploymentId}}));await page.getByRole('button',{name:'Connect enrolled runtime'}).click();await expect(page.locator('.wb-runtime-bar')).toContainText('does not match');await expect(page.getByRole('button',{name:'Refresh',exact:true})).toBeDisabled();});
test('keyboard selection, recorded disclosure, reduced-motion mobile reflow and local layout persistence',async({page})=>{await page.emulateMedia({reducedMotion:'reduce'});await open(page);const button=page.getByRole('button',{name:'Select radio2',exact:true});await button.focus();await page.keyboard.press('Enter');await expect(page.getByRole('complementary',{name:'Selected object inspector'})).toContainText('radio2');await page.getByRole('button',{name:'Fit view',exact:true}).click();expect(await page.evaluate(()=>Object.keys(localStorage).filter(k=>k.startsWith('clab-view:')).length)).toBeGreaterThan(0);await expect(page.locator('.wb-view-tabs')).toContainText('RECORDED EXAMPLE');await page.setViewportSize({width:390,height:844});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBeTruthy();await expect(page.getByRole('button',{name:'Reset layout'})).toBeVisible();});
test('selected link capture drafts are occurrence-scoped, inert and include Lua settings',async({page})=>{
 await open(page);await page.getByRole('button',{name:'Inspect switch1 ethernet-1/3',exact:true}).click();await page.getByRole('button',{name:'Capture & TShark',exact:true}).click();
 await page.getByLabel('PCAP storage filename',{exact:true}).fill('../private.pcap');await expect(page.getByRole('alert')).toContainText('no directory path');await page.getByLabel('PCAP storage filename',{exact:true}).fill('trial.pcap');await expect(page.getByRole('alert')).toHaveCount(0);
 await page.getByLabel('Capture endpoint',{exact:true}).selectOption('1');await page.getByLabel('Capture filter (BPF)',{exact:true}).fill('udp');await page.getByLabel('TShark display filter',{exact:true}).fill('udp.port == 5000');await page.getByLabel('Include Lua settings').check();await page.getByLabel('Lua script reference').fill('reviewed.lua');await page.getByLabel('Lua script arguments').fill('<script>alert(1)</script>');await expect(page.getByRole('button',{name:'Start capture — unavailable'})).toBeDisabled();
 await page.getByRole('button',{name:'Inspect switch1 ethernet-1/2',exact:true}).click();await expect(page.getByLabel('PCAP storage filename',{exact:true})).toHaveValue('');await page.getByRole('button',{name:'Inspect switch1 ethernet-1/3',exact:true}).click();await expect(page.getByLabel('PCAP storage filename',{exact:true})).toHaveValue('trial.pcap');await expect(page.getByLabel('Lua script arguments')).toHaveValue('<script>alert(1)</script>');
 await page.screenshot({path:'test-results/capture-desktop.png',fullPage:true});await page.setViewportSize({width:390,height:844});await page.getByLabel('PCAP storage filename',{exact:true}).scrollIntoViewIfNeeded();expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBeTruthy();await page.screenshot({path:'test-results/capture-mobile.png',fullPage:true});
 await page.getByRole('button',{name:'Reset capture draft'}).click();await expect(page.getByLabel('PCAP storage filename',{exact:true})).toHaveValue('');await expect(page.getByLabel('Include Lua settings')).not.toBeChecked();
});
test('node log and serial views preserve unknown capability and do not imply runtime access',async({page})=>{
 await open(page);await page.getByRole('button',{name:'Select radio2',exact:true}).click();await page.getByRole('button',{name:'Logs',exact:true}).click();const logs=page.getByRole('region',{name:'Selected node logs'});await expect(logs).toContainText('radio2');await expect(logs).toContainText('No logs loaded');await expect(logs.getByRole('button',{name:'Load logs'})).toBeDisabled();
 await page.getByRole('button',{name:'Serial console',exact:true}).click();const consoleView=page.getByRole('region',{name:'Selected node serial console'});await expect(consoleView).toContainText('Not checked');await expect(consoleView.getByRole('button',{name:'Connect serial console'})).toBeDisabled();await page.getByRole('button',{name:'Select switch1',exact:true}).click();await expect(consoleView).toContainText('switch1');await expect(consoleView).not.toContainText('radio2');await page.getByRole('button',{name:'Inspect switch1 ethernet-1/3',exact:true}).click();await expect(page.getByRole('button',{name:'Serial console',exact:true})).toHaveCount(0);await expect(page.getByRole('button',{name:'Overview',exact:true})).toHaveAttribute('aria-pressed','true');
});
