import{test}from'node:test';import assert from'node:assert/strict';import{readFileSync}from'node:fs';
import{captureRequest,captureResult}from'../contracts/capture.ts';import{captureTarget,getCapture}from'../backend/capture.ts';
const g=JSON.parse(readFileSync('experiments/EXP-026-four-radio/declarations.json','utf8'));
import{derivePlan}from'../contracts/enrollment.ts';import{enroll}from'../contracts/multi-observation.ts';
const raw=JSON.parse(readFileSync('experiments/EXP-026-four-radio/native-observation.json','utf8')),binding=enroll(raw,derivePlan(g),'a'.repeat(64),raw.labName),s:any={graph:g,binding};
const e=binding.plan.endpoints.find(e=>e.kind==='linux')!;
const input={jobId:'a'.repeat(32),deploymentId:binding.deploymentId,endpointId:e.endpointId,filename:'trial.pcap',duration:2,snaplen:128,captureFilter:'icmp',displayFilter:'icmp'};
test('capture request bounds and path/command separation',()=>{assert.ok(captureRequest.safeParse(input).success);for(const patch of [{filename:'../secret.pcap'},{filename:'x".pcap'},{duration:11},{snaplen:65536},{captureFilter:'a\nb'},{size:999},{lua:'unreviewed.lua'}])assert.equal(captureRequest.safeParse({...input,...patch}).success,false);});
test('capture target resolves only frozen Linux endpoint identity',()=>{const target=captureTarget(s,input);assert.equal(target.cid,binding.nodes.find(n=>n.nodeId===e.nodeId)!.id);assert.equal(target.item.name,e.declaredInterface);assert.throws(()=>captureTarget(s,{...input,deploymentId:'b'.repeat(64)}),/ASSOCIATION_CONFLICT/);assert.throws(()=>captureTarget(s,{...input,endpointId:binding.plan.endpoints.find(e=>e.kind==='nokia_srlinux')!.endpointId}),/CAPTURE_UNSUPPORTED/);assert.throws(()=>getCapture('a'.repeat(32)),/ARTIFACT_UNAVAILABLE/);});
test('capture metadata rejects oversized artifacts and unreviewed packet fields',()=>{const result={contract:'capture/0.1',id:input.jobId,deploymentId:input.deploymentId,endpointId:input.endpointId,filename:input.filename,sha256:'a'.repeat(64),bytes:24,createdAt:new Date().toISOString(),expiresAt:new Date().toISOString(),limited:false,packets:[],analysis:'complete',completeness:'not_established'};assert.ok(captureResult.safeParse(result).success);assert.equal(captureResult.safeParse({...result,bytes:1048577}).success,false);assert.equal(captureResult.safeParse({...result,packets:[{payload:'private'}]}).success,false);});
import{createServer}from'node:http';import{captureAPI}from'../backend/capture.ts';
test('capture HTTP rejects cross-origin and path/size input before any native operation',async()=>{
 const server=createServer((req,res)=>{void captureAPI(req,res,(server.address() as any).port);});await new Promise<void>(resolve=>server.listen(0,'127.0.0.1',resolve));const port=(server.address() as any).port;
 try{let r=await fetch(`http://127.0.0.1:${port}/api/capture`,{method:'POST',headers:{Origin:'http://other.invalid','Content-Type':'application/json'},body:JSON.stringify(input)});assert.equal(r.status,403);r=await fetch(`http://127.0.0.1:${port}/api/capture`,{method:'POST',body:JSON.stringify({...input,filename:'../private.pcap'})});assert.equal((await r.json()).code,'INVALID_REQUEST');r=await fetch(`http://127.0.0.1:${port}/api/capture`,{method:'POST',body:'x'.repeat(9000)});assert.equal((await r.json()).code,'INVALID_REQUEST');}finally{server.closeAllConnections();await new Promise<void>(resolve=>server.close(()=>resolve()));}
});
