import {test}from'node:test';import assert from'node:assert/strict';import{stateObservationSchema}from'../contracts/observation.ts';import{associateStates}from'./helpers/legacy-association.ts';
const ns='e'.repeat(64),item={name:'eth1',index:7,mac:'02:00:00:00:00:01',type:'veth',operationalState:'up'};
const b={deploymentId:'d'.repeat(64),sourceSha256:'c'.repeat(64),nodes:['left','right'].map((node,i)=>({node:node as 'left'|'right',id:(i?'b':'a').repeat(64),endpoint:{status:'complete',namespace:ns,items:[item]}}))};
const raw=()=>({ok:true,rows:b.nodes.map(n=>({node:n.node,id:n.id,lab:'observation-slice',kind:'linux',purpose:'observation-slice-v1',state:'running',interfaces:structuredClone(n.endpoint),linux:{administrativeState:'up',carrier:'up',source:'linux_netlink_flags',reason:'MATCHED_NATIVE_ATTRIBUTES'}}))});
test('Linux flags are separate from native operstate and never prove peer or continuity',()=>{const r=raw();r.rows[0].linux.administrativeState='down';r.rows[0].linux.carrier='unknown';const g=associateStates(r,b,1);assert.equal(g.contract,'observation/0.3');assert.deepEqual(g.endpoints.map(e=>[e.administrativeState,e.carrier,e.operationalState]),[['down','unknown','up'],['up','up','up']]);assert.equal(g.endpoints[0].peer,'unknown');assert.equal(g.endpoints[0].continuity,'unknown');assert.equal(g.linkHealth,'unknown');});
test('partial Linux failure preserves native evidence and the other endpoint',()=>{const r=raw();r.rows[0].linux={administrativeState:'unknown',carrier:'unknown',source:'unavailable',reason:'SUPPLEMENT_UNAVAILABLE'};const g=associateStates(r,b,1);assert.equal(g.endpoints[0].operationalState,'up');assert.equal(g.endpoints[0].administrativeState,'unknown');assert.equal(g.endpoints[1].carrier,'up');});
test('changed enrolled attributes withhold even successful supplemental facts',()=>{const r=raw();r.rows[0].interfaces.items[0].index=8;const g=associateStates(r,b,1);assert.equal(g.endpoints[0].status,'unresolved');assert.equal(g.endpoints[0].administrativeState,'unknown');assert.equal(g.endpoints[0].supplementReason,'NOT_ASSOCIATED');});
test('exact tuple reuse cannot upgrade continuity',()=>{const a=associateStates(raw(),b,1),replacement=associateStates(raw(),b,2);assert.equal(a.endpoints[0].continuity,'unknown');assert.equal(replacement.endpoints[0].continuity,'unknown');});
test('invented carrier, peer, source, raw fields or unassociated state are rejected',()=>{const g=associateStates(raw(),b,1);for(const change of [(x:any)=>x.endpoints[0].peer='right',(x:any)=>x.endpoints[0].continuity='continuous',(x:any)=>x.endpoints[0].supplementSource='containerlab',(x:any)=>x.endpoints[0].private='/secret',(x:any)=>x.endpoints[0].status='unavailable',(x:any)=>x.endpoints[0].administrativeState='down']){const x=structuredClone(g);change(x);assert.throws(()=>stateObservationSchema.parse(x));}});
