import{test}from'node:test';import assert from'node:assert/strict';import{readFileSync}from'node:fs';import{derivePlan,bindingSchema,planSchema}from'../contracts/legacy/enrollment.ts';import{enroll,associateMulti,parseMultiObservation}from'../contracts/legacy/multi-observation.ts';
const expected=JSON.parse(readFileSync('experiments/EXP-022-multi-endpoint/expectations.json','utf8'));
import{fixture}from'./helpers/multi.ts';

test('independent parallel occurrences and disconnected node retain exact native facts',()=>{const {raw,binding,plan}=fixture();const g=associateMulti(raw,binding,1);assert.equal(g.nodes.length,3);assert.equal(g.endpoints.length,4);assert.equal(new Set(g.endpoints.map(e=>e.endpointId)).size,4);assert.equal(g.endpoints.filter(e=>e.node==='isolated').length,0);assert.equal(g.nodes.find(n=>n.node==='isolated')!.state,'running');for(const l of expected.links)for(const e of l.endpoints){const x=g.endpoints.find(x=>x.linkId===plan.links[l.occurrence].linkId&&x.position===e.position)!;assert.deepEqual([x.node,x.declaredInterface,x.observedInterface,x.nativeAlias,x.status],[e.node,e.declared,e.native,e.alias,'observed']);}});
test('partial node inspection, ambiguity, alias loss and literal absence preserve other occurrences',()=>{for(const reason of ['INTERFACE_INSPECTION_UNAVAILABLE','AMBIGUOUS_INTERFACE','ALIAS_UNRESOLVED']){const {raw,binding}=fixture();raw.rows[0].endpoints[0]={...raw.rows[0].endpoints[0],status:'unavailable',reason,items:[],linux:{administrativeState:'unknown',carrier:'unknown',source:'unavailable',reason:'NOT_ASSOCIATED'}};const g=associateMulti(raw,binding,1);assert.equal(g.endpoints[0].reason,reason);assert.equal(g.endpoints.filter(e=>e.status==='observed').length,3);}const {raw,binding}=fixture();raw.rows[1].endpoints[0].items=[];assert.equal(associateMulti(raw,binding,1).endpoints[1].status,'absent');});
test('full identity replacement rejects; namespace/interface changes and partial enrollment never adopt',()=>{for(const edit of [(r:any)=>r.rows[0].namespace='f'.repeat(64),(r:any)=>r.rows[0].endpoints[0].items[0].index++]){const {raw,binding}=fixture();edit(raw);assert.equal(associateMulti(raw,binding,1).endpoints[0].reason,'IDENTITY_CHANGED');}const {raw,binding,plan}=fixture();raw.rows[0].id='f'.repeat(64);assert.throws(()=>associateMulti(raw,binding,1),/ASSOCIATION_CONFLICT/);const partial=fixture();partial.raw.rows[0].endpoints[0].items=[];const b=enroll(partial.raw,plan,'d'.repeat(64));assert.equal(associateMulti(fixture().raw,b,1).endpoints[0].reason,'NOT_ENROLLED');});
test('unsupported kinds and external roles remain explicit without invented observations',()=>{const {graph,raw}=fixture();graph.nodes[0].kind='unknown-kind';let p=derivePlan(graph);let filtered={ok:true,rows:raw.rows.filter((r:any)=>r.node!=='router')};let b=enroll(filtered,p,'d'.repeat(64));assert.equal(associateMulti(filtered,b,1).endpoints[0].reason,'UNSUPPORTED_KIND');graph.nodes[0].kind='nokia_srlinux';graph.links[0].state='unsupported';p=derivePlan(graph);const r=fixture().raw;for(const n of r.rows)n.endpoints=n.endpoints.filter((e:any)=>e.endpointId!==p.endpoints[0].endpointId&&e.endpointId!==p.endpoints[1].endpointId);b=enroll(r,p,'d'.repeat(64));assert.equal(associateMulti(r,b,1).endpoints[0].reason,'UNSUPPORTED_ROLE');});
test('strict disclosure, reference, bounds and unknown identity/state claims fail closed',()=>{const {raw,binding,plan}=fixture(),g=associateMulti(raw,binding,1);for(const edit of [(x:any)=>x.endpoints[0].rawPath='/private',(x:any)=>x.endpoints[0].endpointId='other',(x:any)=>x.endpoints[0].peer='client',(x:any)=>x.endpoints[0].containerId='f'.repeat(64),(x:any)=>x.endpoints[0].nativeAlias='guess',(x:any)=>x.nodes=Array(9).fill(x.nodes[0]),(x:any)=>x.endpoints=Array(33).fill(x.endpoints[0])]){const x=structuredClone(g);edit(x);assert.throws(()=>parseMultiObservation(x));}assert.throws(()=>planSchema.parse({...plan,links:Array(17).fill(plan.links[0])}));assert.throws(()=>bindingSchema.parse({...binding,nodes:[]}));assert.throws(()=>associateMulti({...raw,private:'x'},binding,1));assert.throws(()=>parseMultiObservation({payload:'x'.repeat(262145)}),/OUTPUT_LIMIT/);});
test('maximum bounded enrollment accepted; one over each collection rejected',()=>{const {plan}=fixture();const p=structuredClone(plan);p.nodes=Array.from({length:8},(_,i)=>({nodeId:`n${i}`,node:`node${i}`,kind:'linux',supported:true}));p.links=Array.from({length:16},(_,i)=>({linkId:`l${i}`,occurrence:i}));p.endpoints=p.links.flatMap(l=>[0,1].map(position=>({endpointId:`${l.linkId}:endpoint:${position}`,linkId:l.linkId,position,nodeId:`n${position}`,node:`node${position}`,kind:'linux',declaredInterface:`eth${l.occurrence+1}`,mode:'literal' as const,reason:'QUALIFIED_PROFILE' as const})));assert.equal(planSchema.parse(p).endpoints.length,32);for(const key of ['nodes','links','endpoints'] as const){const x=structuredClone(p);(x[key] as any[]).push({...x[key][0]});assert.throws(()=>planSchema.parse(x));}});
