import{test}from'node:test';import assert from'node:assert/strict';import{logSnapshotSchema}from'../contracts/node-logs.ts';import{logTarget}from'../backend/node-logs.ts';
const base={contract:'node-logs/0.1',deploymentId:'a'.repeat(64),nodeId:'node:1',sourceSha256:'b'.repeat(64),bundleSha256:'c'.repeat(64),observedAt:new Date().toISOString(),text:'<script>alert(1)</script>\n',truncated:false,tailLines:100,source:'container_stdout_stderr'};
test('log contract allows text markup but rejects control escapes, byte overflow and unknown fields',()=>{assert.equal(logSnapshotSchema.parse(base).text,base.text);for(const extra of [{text:'\x1b]52;c;payload'},{text:'é'.repeat(40000)},{text:'x'.repeat(65537)},{command:'sh'},{tailLines:101}])assert.throws(()=>logSnapshotSchema.parse({...base,...extra}));});
test('log target requires explicit qualification, enrolled deployment, node ID and supported bound container',()=>{const s:any={logCapability:'node-logs/0.1',binding:{deploymentId:base.deploymentId,nodes:[{nodeId:'one',id:'d'.repeat(64)}],plan:{nodes:[{nodeId:'one',supported:true}]}}};assert.equal(logTarget(s,'one',base.deploymentId).id,'d'.repeat(64));assert.throws(()=>logTarget(s,'one','e'.repeat(64)),/ASSOCIATION_CONFLICT/);assert.throws(()=>logTarget(s,'two',base.deploymentId),/INVALID_REQUEST/);assert.throws(()=>logTarget({...s,logCapability:undefined},'one',base.deploymentId),/LOGS_NOT_QUALIFIED/);s.binding.plan.nodes[0].supported=false;assert.throws(()=>logTarget(s,'one',base.deploymentId),/UNSUPPORTED/);s.binding.plan.nodes[0].supported=true;s.binding.nodes[0].id=null;assert.throws(()=>logTarget(s,'one',base.deploymentId),/NODE_UNAVAILABLE/);});
test('transport enforces malformed/output/timeout/cancellation boundaries with a local fake executable',async()=>{
 const{mkdtempSync,writeFileSync,rmSync}=await import('node:fs'),{tmpdir}=await import('node:os'),{join}=await import('node:path'),{logTransport,stopNodeLogs}=await import('../backend/node-logs.ts');const dir=mkdtempSync(join(tmpdir(),'clab-log-test-')),old=process.env.PATH;
 writeFileSync(join(dir,'limactl'),`#!${process.execPath}\nconst mode=process.env.LOG_TEST_MODE;if(mode==='bad')process.stdout.write('not json');else if(mode==='big')process.stdout.write('x'.repeat(600000));else if(mode==='wait')setTimeout(()=>{},30000);else console.log(JSON.stringify({ok:true,text:'test',truncated:false}));`,{mode:0o700});process.env.PATH=dir+':'+old;
 try{assert.equal((await logTransport('fake',[],new AbortController().signal)).text,'test');process.env.LOG_TEST_MODE='bad';await assert.rejects(logTransport('fake',[],new AbortController().signal),/MALFORMED_LOGS/);process.env.LOG_TEST_MODE='big';await assert.rejects(logTransport('fake',[],new AbortController().signal),/OUTPUT_LIMIT/);process.env.LOG_TEST_MODE='wait';const c=new AbortController(),p=logTransport('fake',[],c.signal);c.abort();await assert.rejects(p,/CANCELLED/);await assert.rejects(logTransport('fake',[],new AbortController().signal),/INSPECTION_TIMEOUT/);await stopNodeLogs();}finally{process.env.PATH=old;delete process.env.LOG_TEST_MODE;rmSync(dir,{recursive:true,force:true});}
});

import {logView} from '../apps/web/src/workbench/log-view.ts';
test('local tail then literal filter preserves bounds and does not interpret regex or markup',()=>{
 const text=Array.from({length:100},(_,i)=>`line ${i} ${i===99?'[WARN] <script>.*':''}`).join('\n')+'\n';
 const v=logView(text,25,'[warn]');assert.equal(v.fetched,100);assert.equal(v.window,25);assert.equal(v.matched,1);assert.equal(v.text,'line 99 [WARN] <script>.*');
 assert.equal(logView(text,25,'line 0').matched,0);assert.equal(logView(text,100,'line 0').matched,1);
 assert.equal(logView(text,25,'.*').matched,1);assert.equal(logView('',25,'').fetched,0);assert.equal(logView('one\n\n',25,'').fetched,2);
});
