import{test}from'node:test';import assert from'node:assert/strict';import{profileObservationSchema}from'../contracts/observation.ts';import{associateProfile}from'./helpers/legacy-association.ts';
const info=(i:number)=>({status:'complete',namespace:(i?'f':'e').repeat(64),items:[{name:i?'eth1':'e1-1',alias:i?'':'ethernet-1/1',type:'veth',index:i+7,mac:`02:00:00:00:00:0${i+1}`,operationalState:'up'}]});
const binding={deploymentId:'d'.repeat(64),sourceSha256:'c'.repeat(64),nodes:[{node:'left' as const,id:'a'.repeat(64),endpoint:info(0)},{node:'right' as const,id:'b'.repeat(64),endpoint:info(1)}]};
const raw=()=>({ok:true,rows:binding.nodes.map((n,i)=>({node:n.node,id:n.id,kind:i?'linux':'nokia_srlinux',state:'running',lab:'observation-slice',purpose:'observation-slice-v1',interfaces:info(i),linux:{administrativeState:'up',carrier:'up',source:'linux_netlink_flags',reason:'MATCHED_NATIVE_ATTRIBUTES'}}))});
test('SRL alias is native evidence separate from declaration and actual interface',()=>{const g=associateProfile(raw(),binding,1);assert.equal(g.profile,'SRL-PAIR');assert.deepEqual(g.endpoints.map(e=>[e.node,e.kind,e.declaredInterface,e.observedInterface,e.nativeAlias]),[['left','nokia_srlinux','ethernet-1/1','e1-1','ethernet-1/1'],['right','linux','eth1','eth1','']]);assert.equal(g.endpoints[0].continuity,'unknown');});
test('no guessed alias or substitute Linux kind',()=>{for(const edit of [(r:any)=>r.rows[0].kind='linux',(r:any)=>r.rows[0].interfaces.items[0].alias='',(r:any)=>r.rows[0].interfaces.items[0].alias='ethernet-1/2',(r:any)=>r.rows[0].id='0'.repeat(64)]){const r=raw();edit(r);assert.throws(()=>associateProfile(r,binding,1));}});
test('changed name, index or namespace remains unresolved',()=>{for(const edit of [(r:any)=>r.rows[0].interfaces.items[0].name='different',(r:any)=>r.rows[0].interfaces.items[0].index=100,(r:any)=>r.rows[0].interfaces.namespace='9'.repeat(64)]){const r=raw();edit(r);const g=associateProfile(r,binding,1);assert.equal(g.endpoints[0].status,'unresolved');assert.equal(g.endpoints[0].administrativeState,'unknown');}});
test('missing alias does not prove interface deletion and leaves peer visible',()=>{const r:any=raw();r.rows[0].interfaces={status:'unavailable',reason:'ALIAS_UNRESOLVED',items:[]};const g=associateProfile(r,binding,1);assert.equal(g.endpoints[0].status,'unavailable');assert.equal(g.endpoints[1].status,'observed');r.rows[0].interfaces=info(0);r.rows[0].interfaces.items=[];assert.equal(associateProfile(r,binding,1).endpoints[0].reason,'ALIAS_UNRESOLVED');});
test('profile DTO rejects arbitrary kinds, aliases, properties, peers and conflicting identities',()=>{const g=associateProfile(raw(),binding,1);for(const edit of [(x:any)=>x.endpoints[0].kind='linux',(x:any)=>x.endpoints[0].nativeAlias='hostile',(x:any)=>x.endpoints[0].rawPath='/private',(x:any)=>x.endpoints[0].peer='right',(x:any)=>x.endpoints[0].containerId='0'.repeat(64),(x:any)=>x.endpoints[0].status='absent']){const x=structuredClone(g);edit(x);assert.throws(()=>profileObservationSchema.parse(x));}});
