import{test}from'node:test';import assert from'node:assert/strict';import{mkdtempSync,readFileSync,writeFileSync,rmSync}from'node:fs';import{tmpdir}from'node:os';import{join}from'node:path';import{randomBytes}from'node:crypto';
import{reanalysisRequest}from'../contracts/capture.ts';import{collectCapture,reanalyzeCapture,getCapture,discardCapture}from'../backend/capture.ts';import{derivePlan}from'../contracts/enrollment.ts';import{enroll}from'../contracts/multi-observation.ts';import{enrollDeployment}from'../contracts/deployment.ts';
const request={jobId:'a'.repeat(32),artifactId:'b'.repeat(32),sha256:'c'.repeat(64),displayFilter:'icmp'};
test('reanalysis accepts artifact references only, separate job identity and reviewed options',()=>{assert.ok(reanalysisRequest.safeParse(request).success);for(const p of [{data:'pcap'},{path:'/secret'},{duration:10},{filename:'a.pcap'},{luaId:'unknown'},{luaArgs:[]},{displayFilter:'\n'},{jobId:request.artifactId},{sha256:'bad'}])assert.equal(reanalysisRequest.safeParse({...request,...p}).success,false);});
test('managed reanalysis uses unchanged bytes/TTL; refuses mismatch, expiry, malformed/oversized output, cancellation and capability changes',async()=>{
 const dir=mkdtempSync(join(tmpdir(),'clab-reanalysis-test-')),pathBefore=process.env.PATH,sessionBefore=process.env.CLAB_OBSERVATION_SESSION,clock=Date.now;
 const old=JSON.parse(readFileSync('experiments/EXP-026-four-radio/session.json','utf8')),graph=JSON.parse(readFileSync('experiments/EXP-026-four-radio/declarations.json','utf8')),raw=JSON.parse(readFileSync('experiments/EXP-026-four-radio/native-observation.json','utf8')),binding=enroll(raw,derivePlan(graph),old.binding.deploymentId,raw.labName),inventory={[raw.labName]:old.deployment.containers.map((c:any)=>({ID:c.id,Names:[c.name],Labels:{containerlab:raw.labName,'clab-node-name':c.node,'clab-node-kind':c.kind}}))};
 const file=join(dir,'session.json'),session={...old,graph,binding,sessionFormat:'observation-session/0.4',deployment:enrollDeployment(graph,inventory,raw.labName),expiresAt:new Date(clock()+3600000).toISOString(),captureCapability:'capture/0.1',reanalysisCapability:'reanalysis/0.1'};writeFileSync(file,JSON.stringify(session));
 writeFileSync(join(dir,'limactl'),`#!${process.execPath}\nlet s='';process.stdin.on('data',b=>s+=b);process.stdin.on('end',()=>{const x=JSON.parse(s),m=process.env.REANALYSIS_TEST_MODE;const analysis=process.argv.at(-1).includes('reanalysis');require('fs').appendFileSync(${JSON.stringify(join(dir,'calls'))},JSON.stringify({analysis,input:x})+'\\n');if(m==='bad')return console.log('not JSON');if(m==='big')return process.stdout.write('X'.repeat(200000));const out=analysis?{ok:true,sha256:m==='hash'?'0'.repeat(64):x.sha256,analysis:'complete',packets:[]}:{ok:true,data:Buffer.alloc(24).toString('base64'),limited:false,analysis:'complete',packets:[]};if(m==='fields')out.packets=[{payload:'private'}];setTimeout(()=>console.log(JSON.stringify(out)),m==='timeout'?30000:m==='wait'?180:0);});`,{mode:0o700});
 process.env.PATH=dir+':'+pathBefore;process.env.CLAB_OBSERVATION_SESSION=file;
 const id=()=>randomBytes(16).toString('hex'),endpoint=binding.plan.endpoints.find(e=>e.kind==='linux')!;
 const capture=()=>collectCapture({jobId:id(),deploymentId:binding.deploymentId,endpointId:endpoint.endpointId,filename:'test.pcap',duration:1,snaplen:128,captureFilter:'',displayFilter:''},new AbortController().signal);
 try{
  let a=await capture();const req=()=>({jobId:id(),artifactId:a.id,sha256:a.sha256,displayFilter:'icmp'});
  const b=await reanalyzeCapture(req(),new AbortController().signal);assert.equal(b.sha256,a.sha256);assert.equal(b.capturedAt,a.createdAt);assert.equal(b.expiresAt,a.expiresAt);assert.deepEqual(getCapture(a.id).result,a);assert.equal(getCapture(a.id).data.length,24);
  const calls=readFileSync(join(dir,'calls'),'utf8').trim().split('\n').map(x=>JSON.parse(x));assert.equal(calls.filter(x=>!x.analysis).length,1);assert.equal(calls[1].input.data,Buffer.alloc(24).toString('base64'));
  assert.throws(()=>getCapture('0'.repeat(32)),/ARTIFACT_UNAVAILABLE/);assert.equal(getCapture(a.id).result.id,a.id);
  await assert.rejects(reanalyzeCapture({...req(),sha256:'0'.repeat(64)},new AbortController().signal),/ARTIFACT_MISMATCH/);
  for(const [mode,error]of [['hash',/ARTIFACT_MISMATCH/],['bad',/MALFORMED_ANALYSIS/],['big',/OUTPUT_LIMIT/],['fields',/./]] as const){process.env.REANALYSIS_TEST_MODE=mode;await assert.rejects(reanalyzeCapture(req(),new AbortController().signal),error);assert.equal(getCapture(a.id).result.id,a.id);}
  process.env.REANALYSIS_TEST_MODE='wait';const c=new AbortController(),pending=reanalyzeCapture(req(),c.signal);await assert.rejects(capture(),/BUSY/);c.abort();await assert.rejects(pending,/CANCELLED/);assert.equal(getCapture(a.id).result.id,a.id);
  const{createServer}=await import('node:http'),{captureAPI}=await import('../backend/capture.ts');const server=createServer((req,res)=>{void captureAPI(req,res,(server.address() as any).port);});await new Promise<void>(resolve=>server.listen(0,'127.0.0.1',resolve));
  try{const next=reanalyzeCapture(req(),new AbortController().signal);const response=await fetch(`http://127.0.0.1:${(server.address() as any).port}/api/capture/cancel`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({jobId:'0'.repeat(32)})});assert.equal(response.status,200);assert.equal((await next).artifactId,a.id);}finally{server.closeAllConnections();await new Promise<void>(resolve=>server.close(()=>resolve()));}
  process.env.REANALYSIS_TEST_MODE='timeout';await assert.rejects(reanalyzeCapture(req(),new AbortController().signal),/CAPTURE_TIMEOUT/);assert.equal(getCapture(a.id).result.id,a.id);process.env.REANALYSIS_TEST_MODE='wait';
  const expiring=reanalyzeCapture(req(),new AbortController().signal);Date.now=()=>clock()+300001;await assert.rejects(expiring,/ARTIFACT_UNAVAILABLE/);Date.now=clock;assert.throws(()=>getCapture(a.id),/ARTIFACT_UNAVAILABLE/);
  delete process.env.REANALYSIS_TEST_MODE;a=await capture();process.env.REANALYSIS_TEST_MODE='wait';const revoked=reanalyzeCapture(req(),new AbortController().signal);writeFileSync(file,JSON.stringify({...session,reanalysisCapability:undefined}));await assert.rejects(revoked,/ARTIFACT_UNAVAILABLE/);assert.throws(()=>getCapture(a.id),/ARTIFACT_UNAVAILABLE/);
  writeFileSync(file,JSON.stringify(session));delete process.env.REANALYSIS_TEST_MODE;a=await capture();const replaced=a.id;a=await capture();await assert.rejects(reanalyzeCapture({...req(),artifactId:replaced},new AbortController().signal),/ARTIFACT_UNAVAILABLE/);
 }finally{Date.now=clock;discardCapture();process.env.PATH=pathBefore;if(sessionBefore===undefined)delete process.env.CLAB_OBSERVATION_SESSION;else process.env.CLAB_OBSERVATION_SESSION=sessionBefore;delete process.env.REANALYSIS_TEST_MODE;rmSync(dir,{recursive:true,force:true});}
});
