import{test}from'node:test';import assert from'node:assert/strict';import{readFileSync}from'node:fs';
import{fixture}from'./helpers/multi.ts';import{derivePlan}from'../contracts/enrollment.ts';import{enrollDeployment}from'../contracts/deployment.ts';import{enroll,associateMulti}from'../contracts/multi-observation.ts';import{presentation}from'../apps/web/src/workbench/model.ts';
const graph=JSON.parse(readFileSync('experiments/EXP-026-four-radio/declarations.json','utf8'));
test('every native endpoint attaches to its exact port handle without changing input',()=>{const before=JSON.stringify(graph),p=presentation(graph);assert.equal(p.cards.length,8);assert.equal(p.wires.length,7);for(const l of graph.links){const w=p.wires.find(w=>w.id===l.id)!;for(const [i,e]of l.endpoints.entries()){assert.equal(i?w.target:w.source,e.nodeId);const c=p.cards.find(c=>c.id===e.nodeId)!;assert.equal(c.ports.find(p=>p.id===(i?w.targetHandle:w.sourceHandle))!.name,e.interface);}}assert.equal(JSON.stringify(graph),before);for(const a of p.cards)for(const b of p.cards)if(a.id!==b.id)assert.ok(a.position.x+210<=b.position.x||b.position.x+210<=a.position.x||a.position.y+a.height<=b.position.y||b.position.y+b.height<=a.position.y);});
test('renamed and differently sized inventories share generic enrollment and observation rules',()=>{
 for(const count of [2,3,4]){const f=fixture(),g=f.graph;g.provenance.bundleId='independent-'+count;g.provenance.sourceId=g.provenance.bundleId;
  if(count===2){const removed=g.nodes.find((n:any)=>n.name==='isolated')!.id;g.nodes=g.nodes.filter((n:any)=>n.id!==removed);g.dependencies=g.dependencies.filter((d:any)=>d.ownerId!==removed);}
  if(count===4){const added={...g.nodes[0],id:g.revision+':new-node',name:'extra'};g.nodes.push(added);const previous=g.links[0].endpoints[1];g.links[1].endpoints=[{...previous,interface:'chain0'},{...previous,nodeId:added.id,nodeLabel:added.name,interface:'chain1'}];}
  for(const [i,n]of g.nodes.entries()){n.name='device_'+i;for(const l of g.links)for(const e of l.endpoints)if(e.nodeId===n.id)e.nodeLabel=n.name;}
  g.nodes.reverse();const plan=derivePlan(g),lab='renamed-lab-'+count;
  const inventory={[lab]:plan.nodes.map((n,i)=>({ID:String(i+1).repeat(64),Names:['independent-prefix-'+i],Labels:{containerlab:lab,'clab-node-name':n.node,'clab-node-kind':n.kind}}))};
  const deployment=enrollDeployment(g,inventory,lab);assert.equal(deployment.containers.length,count);
  const raw={ok:true,labName:lab,rows:plan.nodes.filter(n=>n.supported).map(n=>({node:n.node,kind:n.kind,id:deployment.containers.find(c=>c.node===n.node)!.id,state:'running',namespace:'b'.repeat(64),endpoints:plan.endpoints.filter(e=>e.nodeId===n.nodeId&&e.mode!=='unsupported').map((e,i)=>({endpointId:e.endpointId,status:'complete',reason:'NATIVE_INTERFACE_INVENTORY',items:[{name:e.mode==='literal'?e.declaredInterface:'native'+i,alias:e.mode==='native_alias'?e.declaredInterface:'',index:i+1,mac:'aa:bb:cc:dd:ee:ff',type:'veth',operationalState:'up'}],linux:{administrativeState:'unknown',carrier:'unknown',source:'unavailable',reason:'NOT_ASSOCIATED'}}))}))};
  const binding=enroll(raw,plan,'c'.repeat(64),lab),result=associateMulti(raw,binding,1);assert.equal(result.contract,'observation/0.9');assert.equal(result.nodes.length,count);assert.equal(result.labName,lab);assert.throws(()=>associateMulti({...raw,labName:'other'},binding,2));const replaced=structuredClone(raw);replaced.rows[0].id='f'.repeat(64);assert.throws(()=>associateMulti(replaced,binding,2),/ASSOCIATION_CONFLICT/);
  assert.throws(()=>enrollDeployment(g,inventory,'wrong-lab'));assert.equal(presentation(g).cards.filter(c=>!c.boundary).length,count);
 }
});
test('single-ended, dangling and disconnected occurrences remain explicit presentation objects',()=>{const f=fixture(),g=f.graph;g.links[0].endpoints.pop();g.links[1].endpoints[1].nodeId=null;g.links[1].endpoints[1].nodeLabel='outside';const p=presentation(g);assert.equal(p.wires.length,2);assert.equal(p.cards.filter(c=>!c.boundary).length,g.nodes.length);assert.equal(p.cards.filter(c=>c.boundary).length,2);assert.equal(p.wires.filter(w=>w.stub).length,2);});

test('current session checks general deployment binding before transport; historical sessions cannot activate',async()=>{
 const{mkdtempSync,writeFileSync,rmSync}=await import('node:fs'),{tmpdir}=await import('node:os'),{join}=await import('node:path'),{readObservationSession}=await import('../backend/observation-session.ts');
 const old=JSON.parse(readFileSync('experiments/EXP-026-four-radio/session.json','utf8')),raw=JSON.parse(readFileSync('experiments/EXP-026-four-radio/native-observation.json','utf8')),plan=derivePlan(graph),binding=enroll(raw,plan,old.binding.deploymentId,raw.labName);
 const inventory={[raw.labName]:old.deployment.containers.map((c:any)=>({ID:c.id,Names:[c.name],Labels:{containerlab:raw.labName,'clab-node-name':c.node,'clab-node-kind':c.kind}}))};
 const session={...old,sessionFormat:'observation-session/0.4',expiresAt:new Date(Date.now()+60000).toISOString(),binding,deployment:enrollDeployment(graph,inventory,raw.labName)},dir=mkdtempSync(join(tmpdir(),'gui-session-')),file=join(dir,'session.json');
 try{writeFileSync(file,JSON.stringify(session));assert.equal(readObservationSession(file).binding.plan.version,'enrollment/0.3');for(const edit of [(s:any)=>s.deployment.containers[0].id='f'.repeat(64),(s:any)=>s.binding.labName='wrong',(s:any)=>s.deployment.bundleSha256='b'.repeat(64),(s:any)=>s.expiresAt='2000-01-01',(s:any)=>s.sessionFormat='observation-session/0.3']){const s=structuredClone(session);edit(s);writeFileSync(file,JSON.stringify(s));assert.throws(()=>readObservationSession(file));}}finally{rmSync(dir,{recursive:true});}
});

test('unsupported kinds stay explicit and general collection ceilings remain enforced',()=>{const f=fixture(),g=f.graph;g.nodes[0].kind='unqualified-appliance';const p=derivePlan(g),raw={...f.raw,labName:'arbitrary-lab',rows:f.raw.rows.filter((r:any)=>r.node!==g.nodes[0].name)};const b=enroll(raw,p,'d'.repeat(64),'arbitrary-lab'),o=associateMulti(raw,b,1);assert.equal(o.nodes.length,g.nodes.length);assert.equal(o.endpoints.length,4);assert.ok(o.endpoints.some(e=>e.reason==='UNSUPPORTED_KIND'));while(g.nodes.length<9)g.nodes.push({...g.nodes[0],id:g.revision+':extra'+g.nodes.length,name:'extra'+g.nodes.length});assert.throws(()=>derivePlan(g));});
