import assert from'node:assert/strict';import{readFileSync,writeFileSync,mkdirSync}from'node:fs';import{join}from'node:path';import{inspectNative}from'../../backend/observation.ts';import{associateMulti}from'../../contracts/multi-observation.ts';
const s=JSON.parse(readFileSync(process.env.CLAB_OBSERVATION_SESSION!,'utf8'));const expected=JSON.parse(readFileSync('experiments/EXP-023-capacity/expectations.json','utf8')).find((e:any)=>e.profile===s.profile);assert.ok(expected);const dir=join(process.env.CLAB_CAPACITY_EVIDENCE_DIR??'experiments/EXP-023-capacity',s.profile+'-'+Date.now());mkdirSync(dir);writeFileSync(join(dir,'session.json'),JSON.stringify(s,null,2)+'\n');
function check(g:any){
 assert.equal(g.nodes.length,expected.nodes.length);assert.equal(g.endpoints.length,expected.links.length*2);assert.equal(s.graph.links.length,expected.links.length);
 for(const n of expected.nodes){const declared=s.graph.nodes.find((x:any)=>x.name===n.name),actual=g.nodes.find((x:any)=>x.node===n.name);assert.ok(declared);assert.equal(actual.nodeId,declared.id);assert.equal(actual.kind,n.kind);assert.equal(actual.state,'running');assert.equal(g.endpoints.filter((e:any)=>e.node===n.name).length,n.endpointCount);}
 for(const l of expected.links){const declared=s.graph.links.find((x:any)=>x.occurrence===l.occurrence);assert.equal(declared.type,'veth');for(const e of l.endpoints){const x=g.endpoints.find((x:any)=>x.linkId===declared.id&&x.position===e.position);assert.equal(x.endpointId,declared.id+':endpoint:'+e.position);assert.deepEqual([x.node,x.declaredInterface,x.observedInterface,x.nativeAlias,x.status],[e.node,e.declared,e.native,e.alias,'observed']);assert.equal(x.peer,'unknown');assert.equal(x.continuity,'unknown');}}
}
async function sample(i:number){const start=performance.now(),raw=await inspectNative(s.vm),received=performance.now(),g=associateMulti(raw,s.binding,i),validated=performance.now();check(g);const dtoBytes=Buffer.byteLength(JSON.stringify(g));assert.ok(received-start<9000);assert.ok(dtoBytes<=262144);return {transportMs:received-start,dtoValidationMs:validated-received,dtoBytes,snapshot:g};}
const samples:any[]=[];let warmup:any;
try{warmup=await sample(1);for(let i=0;i<20;i++){await new Promise(r=>setTimeout(r,1100));samples.push(await sample(i+2));}console.log('PASS '+s.profile+': 20 independently checked host samples');}finally{writeFileSync(join(dir,'host.json'),JSON.stringify({warmup,samples},null,2)+'\n');}
