import{test}from'node:test';import assert from'node:assert/strict';import{readFileSync,writeFileSync,mkdirSync}from'node:fs';import{execFileSync}from'node:child_process';import{observe}from'../../backend/observation.ts';
const wait=()=>new Promise(r=>setTimeout(r,1100));
test('actual bounded multi endpoint transitions and outdated enrollment',async()=>{
 assert.ok(process.env.CLAB_OBSERVATION_SESSION);const s=JSON.parse(readFileSync(process.env.CLAB_OBSERVATION_SESSION!,'utf8'));assert.equal(s.profile,'MULTI-ENDPOINT-V2');const dir='experiments/EXP-022-multi-endpoint/attempt-'+Date.now();mkdirSync(dir);const evidence:any[]=[];const expected=JSON.parse(readFileSync('experiments/EXP-022-multi-endpoint/expectations.json','utf8'));
 const guest=(...a:string[])=>execFileSync('limactl',['shell',s.vm,'sudo',...a],{timeout:180000,stdio:'pipe'}).toString();const router=s.binding.nodes.find((n:any)=>n.node==='router').id;const pid=()=>guest('docker','inspect','--format','{{.State.Pid}}',router).trim();const ip=(...a:string[])=>guest('nsenter','-t',pid(),'-n','ip',...a);
 const snap=async(stage:string)=>{await wait();const started=Date.now();const g:any=await observe();evidence.push({stage,hostElapsedMs:Date.now()-started,snapshot:g});return g;};const endpoint=(g:any,node:string,name:string)=>g.endpoints.find((e:any)=>e.node===node&&e.declaredInterface===name);
 try{
  let g=await snap('initial');assert.equal(g.contract,'observation/0.5');assert.equal(g.nodes.length,3);assert.equal(g.endpoints.length,4);for(const l of expected.links)for(const e of l.endpoints){const actual=endpoint(g,e.node,e.declared);assert.equal(actual.observedInterface,e.native);assert.equal(actual.nativeAlias,e.alias);assert.equal(actual.status,'observed');}assert.equal(g.endpoints.filter((e:any)=>e.node==='isolated').length,0);assert.equal(g.nodes.find((n:any)=>n.node==='isolated').state,'running');
  const unaffected=endpoint(g,'router','ethernet-1/2');ip('link','set','e1-1','down');g=await snap('first-link-down');assert.equal(endpoint(g,'router','ethernet-1/1').administrativeState,'down');assert.equal(endpoint(g,'router','ethernet-1/2').administrativeState,unaffected.administrativeState);assert.equal(endpoint(g,'client','eth2').status,'observed');
  ip('link','set','e1-1','up');g=await snap('first-link-up');assert.equal(endpoint(g,'router','ethernet-1/1').administrativeState,'up');
  ip('link','set','e1-1','alias','qualification-wrong-alias');g=await snap('first-alias-lost');assert.equal(endpoint(g,'router','ethernet-1/1').reason,expected.aliasLoss);assert.equal(endpoint(g,'router','ethernet-1/2').status,'observed');ip('link','set','e1-1','alias','ethernet-1/1');await snap('same-interface-alias-restored');
  // Native duplicate aliases on two actual veths; no fabricated raw inventory.
  ip('link','set','e1-2','alias','ethernet-1/1');g=await snap('ambiguous-native-alias');assert.equal(endpoint(g,'router','ethernet-1/1').reason,expected.duplicateAlias);assert.equal(endpoint(g,'client','eth2').status,'observed');ip('link','set','e1-2','alias','ethernet-1/2');
  ip('link','del','e1-1');g=await snap('first-link-removed');assert.equal(endpoint(g,'router','ethernet-1/1').reason,expected.aliasLoss);assert.equal(endpoint(g,'client','eth1').reason,expected.literalMissing);assert.equal(endpoint(g,'router','ethernet-1/2').status,'observed');assert.equal(endpoint(g,'client','eth2').status,'observed');
  // Same name with different kernel attributes cannot inherit enrollment.
  ip('link','add','e1-1','type','veth','peer','name','qpeer');ip('link','set','e1-1','alias','ethernet-1/1');g=await snap('interface-replacement');assert.equal(endpoint(g,'router','ethernet-1/1').reason,'IDENTITY_CHANGED');
  guest('docker','stop','--time','1',router);g=await snap('one-node-stopped');assert.equal(endpoint(g,'router','ethernet-1/2').reason,'NODE_NOT_RUNNING');assert.equal(endpoint(g,'client','eth2').reason,'MISSING_FROM_NATIVE_INVENTORY');assert.equal(g.nodes.find((n:any)=>n.node==='client').state,'running');assert.equal(g.nodes.find((n:any)=>n.node==='isolated').state,'running');
  guest('docker','start',router);g=await snap('namespace-restarted');assert.notEqual(endpoint(g,'router','ethernet-1/2').status,'observed');
  await wait();const ctrl=new AbortController(),pending=observe(ctrl.signal);ctrl.abort();await assert.rejects(()=>pending,/CANCELLED/);evidence.push({stage:'cancel',result:'CANCELLED'});
  guest('containerlab','destroy','--topo','/opt/observation-slice/topology.clab.yml','--cleanup');g=await snap('lab-removed');assert.ok(g.endpoints.every((e:any)=>e.reason==='CONTAINER_ABSENT'));
  guest('containerlab','deploy','--topo','/opt/observation-slice/topology.clab.yml');await wait();await assert.rejects(()=>observe(),/ASSOCIATION_CONFLICT/);evidence.push({stage:'same-name-redeployment',result:expected.replacement});
 }finally{writeFileSync(dir+'/results.json',JSON.stringify(evidence,null,2)+'\n');}
});
