import test from 'node:test';import assert from 'node:assert/strict';import {LinkCapture,linkCaptureRequest} from '../../backend/live/capture.ts';
const hash='a'.repeat(64),job='b'.repeat(32);
function setup(call?:any){const graph:any={revision:'revision',provenance:{sourceSha256:hash,bundleSha256:hash},links:[{id:'link',type:'veth',state:'declared',externalRole:'',endpoints:[{nodeId:'n',referenceState:'declared'},{nodeId:'m',referenceState:'declared'}]}]};const binding:any={deploymentId:hash,sourceSha256:hash,plan:{bundleSha256:hash,endpoints:[{position:0,linkId:'link',kind:'linux',mode:'literal',nodeId:'n',endpointId:'link:0',declaredInterface:'eth1'}]},nodes:[{nodeId:'n',node:'node',id:hash,namespace:hash,endpoints:[{endpointId:'link:0',item:{name:'eth1',type:'veth'}}]}]};const bytes=Buffer.alloc(24);bytes.writeUInt32LE(0xa1b2c3d4);bytes.writeUInt16LE(2,4);bytes.writeUInt16LE(4,6);bytes.writeUInt32LE(128,16);bytes.writeUInt32LE(1,20);const context={graph,binding,deployment:{},project:'project'};const capture=new LinkCapture(()=>context,call??(async()=>({data:bytes.toString('base64'),limited:false,packets:[],analysis:'complete'})));return{capture,context,bytes};}
const request={jobId:job,deploymentId:hash,linkId:'link',filename:'link.pcap',duration:1,snaplen:128,captureFilter:'',displayFilter:''};
test('filename is a basename; no client endpoint or arbitrary Lua path accepted',()=>{for(const change of [{filename:'../secret.pcap'},{endpointId:'other'},{luaId:'/tmp/script.lua'}])assert.equal(linkCaptureRequest.safeParse({...request,...change}).success,false);});
test('one selected link produces actual hash-bound bytes and chosen download name',async()=>{const{capture,bytes}=setup();const result=await capture.capture(request,new AbortController().signal);assert.equal(result.filename,'link.pcap');assert.equal(result.endpointId,'link:0');assert.deepEqual(capture.get(job).data,bytes);capture.discard();assert.throws(()=>capture.get(job),/UNAVAILABLE/);});
test('malformed worker PCAP cannot become a downloadable artifact',async()=>{const{capture}=setup(async()=>({data:Buffer.alloc(24).toString('base64'),limited:false,packets:[],analysis:'complete'}));await assert.rejects(capture.capture(request,new AbortController().signal),/MALFORMED_CAPTURE/);assert.throws(()=>capture.get(job),/UNAVAILABLE/);});
test('late completion after cancellation cannot publish an artifact',async()=>{let release:any;const{capture}=setup(()=>new Promise(resolve=>{release=resolve;}));const ctrl=new AbortController();const result=capture.capture(request,ctrl.signal);ctrl.abort();release({});await assert.rejects(result,/CANCELLED/);assert.throws(()=>capture.get(job),/UNAVAILABLE/);});
test('replacement enrollment revokes retained bytes',async()=>{const{capture,context}=setup();await capture.capture(request,new AbortController().signal);context.binding.deploymentId='c'.repeat(64);assert.throws(()=>capture.get(job),/UNAVAILABLE/);});
