import {chromium,expect} from '@playwright/test';import {writeFileSync} from 'node:fs';import {resolve} from 'node:path';
if(process.env.CLAB_INSTALLED_QUALIFY!=='LIVE-002')throw Error('Explicit opt-in required');
const ev=resolve(import.meta.dirname,'../../artifacts/implementation/LIVE-002');const browser=await chromium.launch(),page=await browser.newPage();let result={scope:'Actual installed browser/API',invalidFilename:'NOT_RUN',cancel:'NOT_RUN',cancelledDownload:'NOT_RUN',stop:'NOT_RUN'};
try{
 await page.goto('http://127.0.0.1:4173');const deployed=page.waitForResponse(r=>r.url().endsWith('/api/live/go'));await page.getByRole('button',{name:'GO',exact:true}).click();const snap=await(await deployed).json();if(snap.lifecycle?.phase!=='running')throw Error('DEPLOYMENT_FAILED');
 const bad=await page.evaluate(async({deploymentId,linkId})=>(await fetch('/api/live/capture',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({jobId:'c'.repeat(32),deploymentId,linkId,filename:'../escape.pcap',duration:1,snaplen:128,captureFilter:'',displayFilter:''})})).status,{deploymentId:snap.lifecycle.deploymentId,linkId:snap.graph.links[0].id});if(bad!==422)throw Error('FILENAME_ACCEPTED');result.invalidFilename='PASS';
 await page.getByRole('button',{name:'Inspect sender eth1'}).click();await page.getByLabel('Duration (seconds)').fill('10');const req=page.waitForRequest(r=>r.url().endsWith('/api/live/capture'));await page.getByRole('button',{name:'Start capture',exact:true}).click();const job=(await req).postDataJSON().jobId;await page.waitForTimeout(500);await page.getByRole('button',{name:'Cancel capture',exact:true}).click();await expect(page.getByText('Cancelled. Native capture cleanup is bounded; no cancelled result will be displayed.')).toBeVisible();result.cancel='PASS';
 await page.waitForTimeout(12000);const status=await page.evaluate(async id=>(await fetch('/api/live/capture/'+id+'/download')).status,job);if(status!==422)throw Error('CANCELLED_ARTIFACT_DISCLOSED');result.cancelledDownload='PASS';
 const stopped=page.waitForResponse(r=>r.url().endsWith('/api/live/stop'));await page.getByRole('button',{name:'Stop lab',exact:true}).click();if((await(await stopped).json()).lifecycle?.phase!=='stopped')throw Error('STOP_FAILED');result.stop='PASS';
}catch(e){result.failure=e.message;process.exitCode=1;}finally{await browser.close();writeFileSync(ev+'/installed-faults.json',JSON.stringify(result,null,2)+'\n');console.log(result);}
