import {captureFormErrors,captureFeedback} from './capture-presentation';
import React,{useState,useEffect,useRef} from 'react';
import {captureResult,reanalysisResult,reviewedLua,type CaptureResult,type ReanalysisResult} from '../../contracts/capture';
const messages:Record<string,string>={LINK_CAPTURE_UNSUPPORTED:'This native link shape has no qualified capture point.',LINK_CAPTURE_UNAVAILABLE:'No enrolled Linux capture point is available for this link.',ASSOCIATION_CONFLICT:'The runtime identity changed. Capture was refused.',ARTIFACT_UNAVAILABLE:'The capture expired or its deployment changed.',BUSY:'The runtime is busy. Try again shortly.',INVALID_CAPTURE_REQUEST:'Check the filename, duration, filters and file settings.',CAPTURE_FAILED:'Capture failed. Check the capture filter and runtime availability.',CAPTURE_TIMEOUT:'Capture exceeded its time limit.',LUA_INTEGRITY:'Reviewed Lua integrity check failed.',MALFORMED_CAPTURE:'Invalid capture data was rejected.'};
const id=()=>crypto.randomUUID().replaceAll('-','');
export function Capture({linkId,deploymentId,ready}:{linkId:string;deploymentId:string|null;ready:boolean}){
 const [filename,setFilename]=useState('capture.pcap'),[duration,setDuration]=useState(5),[snaplen,setSnaplen]=useState(65535),[filter,setFilter]=useState(''),[display,setDisplay]=useState(''),[lua,setLua]=useState(false),[result,setResult]=useState<CaptureResult|null>(null),[analysis,setAnalysis]=useState<ReanalysisResult|null>(null),[busy,setBusy]=useState(false),[status,setStatus]=useState('No capture file has been created.');
 const request=useRef<AbortController|null>(null),generation=useRef(0);const [now,setNow]=useState(Date.now());
 useEffect(()=>{const timer=setInterval(()=>setNow(Date.now()),1000);return()=>{clearInterval(timer);generation.current++;request.current?.abort();};},[]);
 const available=Boolean(result&&Date.parse(result.expiresAt)>now&&ready&&result.deploymentId===deploymentId);
 const errors=captureFormErrors({filename,duration,snaplen,captureFilter:filter,displayFilter:display});
 function cancel(){generation.current++;request.current?.abort();request.current=null;setBusy(false);setStatus('Cancelled. Native capture cleanup is bounded; no cancelled result will be displayed.');}
 async function run(reanalyze=false){if(!ready||!deploymentId||request.current||(!reanalyze&&Object.keys(errors).length)||(reanalyze&&errors.displayFilter))return;const ctrl=new AbortController(),ticket=++generation.current;request.current=ctrl;setBusy(true);setStatus(reanalyze?'Analyzing the same PCAP…':'Capturing selected link…');if(!reanalyze){setResult(null);setAnalysis(null);}
 try{const body=reanalyze?{jobId:id(),artifactId:result!.id,sha256:result!.sha256,displayFilter:display,...(lua?{luaId:reviewedLua.id}:{})}:{jobId:id(),deploymentId,linkId,filename,duration,snaplen,captureFilter:filter,displayFilter:display,...(lua?{luaId:reviewedLua.id}:{})};const response=await fetch('/api/live/capture'+(reanalyze?'/analyze':''),{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body),signal:ctrl.signal});const raw=await response.text();if(raw.length>131072)throw Error('OUTPUT_LIMIT');const x=JSON.parse(raw);if(!response.ok)throw Error(x.code);if(ticket!==generation.current||ctrl.signal.aborted)return;
 if(reanalyze){const next=reanalysisResult.parse(x.result);if(next.artifactId!==result!.id||next.sha256!==result!.sha256||next.deploymentId!==deploymentId)throw Error('ASSOCIATION_CONFLICT');setAnalysis(next);}else{const next=captureResult.parse(x.result);if(next.deploymentId!==deploymentId)throw Error('ASSOCIATION_CONFLICT');setResult(next);}setStatus(reanalyze?'Reanalysis finished.':'Capture finished.');
 }catch(e){if(ticket===generation.current)setStatus(messages[e instanceof Error?e.message:'']??'Capture or analysis could not complete. Existing artifact, if any, is unchanged.');}finally{if(ticket===generation.current){request.current=null;setBusy(false);}}}
 const shown=analysis??result,feedback=result?captureFeedback(result,analysis,now):null;
 return <section aria-label="Link capture settings"><label>PCAP filename<input value={filename} aria-invalid={Boolean(errors.filename)} aria-describedby={errors.filename?'capture-error-filename':undefined} onChange={e=>setFilename(e.target.value)} maxLength={128}/></label><label>Duration (seconds)<input type="number" min={1} max={10} value={duration} aria-invalid={Boolean(errors.duration)} aria-describedby={errors.duration?'capture-error-duration':undefined} onChange={e=>setDuration(Number(e.target.value))}/></label><label>Snapshot length (bytes)<input type="number" min={64} max={65535} value={snaplen} aria-invalid={Boolean(errors.snaplen)} aria-describedby={errors.snaplen?'capture-error-snaplen':undefined} onChange={e=>setSnaplen(Number(e.target.value))}/></label><label>Capture filter<input value={filter} aria-invalid={Boolean(errors.captureFilter)} aria-describedby={errors.captureFilter?'capture-error-captureFilter':undefined} onChange={e=>setFilter(e.target.value)} maxLength={1024}/></label><label>TShark display filter<input value={display} aria-invalid={Boolean(errors.displayFilter)} aria-describedby={errors.displayFilter?'capture-error-displayFilter':undefined} onChange={e=>setDisplay(e.target.value)} maxLength={1024}/></label><label>Reviewed Lua<select value={lua?'reviewed':'none'} onChange={e=>setLua(e.target.value==='reviewed')}><option value="none">None</option><option value="reviewed">{reviewedLua.label}</option></select></label><button disabled={!ready||busy||Boolean(Object.keys(errors).length)} onClick={()=>void run()}>Start capture</button><button disabled={!busy} onClick={cancel}>Cancel capture</button><p role="status">{status}</p>{Object.entries(errors).map(([field,message])=><p key={field} id={`capture-error-${field}`} role="alert">{message}</p>)}<p>One PCAP, maximum 1 MiB, retained in application memory for 5 minutes. No automatic rotation or persistent file storage.</p>{result&&<><p>{result.filename} · {result.bytes} bytes</p>{feedback?.limit&&<p role="status">{feedback.limit}</p>}<p>{feedback?.retention}</p>{available?<a href={`/api/live/capture/${result.id}/download`} download={result.filename}>Save PCAP</a>:<p>Artifact expired or deployment unavailable.</p>}<button disabled={!available||busy||Boolean(errors.displayFilter)} onClick={()=>void run(true)}>Reanalyze same PCAP</button></>}{shown&&<><p>{feedback?.analysis}</p><div aria-label="Captured packet rows" tabIndex={0} style={{overflow:'auto',maxHeight:320}}><table><thead><tr><th>Frame</th><th>Bytes</th><th>Protocol</th></tr></thead><tbody>{shown.packets.map(p=><tr key={p.number}><td>{p.number}</td><td>{p.bytes}</td><td>{p.protocol}</td></tr>)}</tbody></table></div></>}</section>;
}
