import React,{useState,useEffect,useRef} from 'react';
import {captureResult,reanalysisResult,reviewedLua,type CaptureResult,type ReanalysisResult} from '../../contracts/capture';
const messages:Record<string,string>={LINK_CAPTURE_UNSUPPORTED:'This native link shape has no qualified capture point.',LINK_CAPTURE_UNAVAILABLE:'No enrolled Linux capture point is available for this link.',ASSOCIATION_CONFLICT:'The runtime identity changed. Capture was refused.',ARTIFACT_UNAVAILABLE:'The capture expired or its deployment changed.',BUSY:'The runtime is busy. Try again shortly.',INVALID_CAPTURE_REQUEST:'Check the filename, duration, filters and file settings.',CAPTURE_FAILED:'Capture failed. Check the capture filter and runtime availability.',CAPTURE_TIMEOUT:'Capture exceeded its time limit.',LUA_INTEGRITY:'Reviewed Lua integrity check failed.',MALFORMED_CAPTURE:'Invalid capture data was rejected.'};
const id=()=>crypto.randomUUID().replaceAll('-','');
export function Capture({linkId,deploymentId,ready}:{linkId:string;deploymentId:string|null;ready:boolean}){
 const [filename,setFilename]=useState('capture.pcap'),[duration,setDuration]=useState(5),[snaplen,setSnaplen]=useState(65535),[filter,setFilter]=useState(''),[display,setDisplay]=useState(''),[lua,setLua]=useState(false),[result,setResult]=useState<CaptureResult|null>(null),[analysis,setAnalysis]=useState<ReanalysisResult|null>(null),[busy,setBusy]=useState(false),[status,setStatus]=useState('No capture file has been created.');
 const request=useRef<AbortController|null>(null),generation=useRef(0);const [now,setNow]=useState(Date.now());
 useEffect(()=>{const timer=setInterval(()=>setNow(Date.now()),1000);return()=>{clearInterval(timer);generation.current++;request.current?.abort();};},[]);
 const available=Boolean(result&&Date.parse(result.expiresAt)>now&&ready&&result.deploymentId===deploymentId);
 function cancel(){generation.current++;request.current?.abort();request.current=null;setBusy(false);setStatus('Cancelled. Native capture cleanup is bounded; no cancelled result will be displayed.');}
 async function run(reanalyze=false){if(!ready||!deploymentId||request.current)return;const ctrl=new AbortController(),ticket=++generation.current;request.current=ctrl;setBusy(true);setStatus(reanalyze?'Analyzing the same PCAP…':'Capturing selected link…');if(!reanalyze){setResult(null);setAnalysis(null);}
 try{const body=reanalyze?{jobId:id(),artifactId:result!.id,sha256:result!.sha256,displayFilter:display,...(lua?{luaId:reviewedLua.id}:{})}:{jobId:id(),deploymentId,linkId,filename,duration,snaplen,captureFilter:filter,displayFilter:display,...(lua?{luaId:reviewedLua.id}:{})};const response=await fetch('/api/live/capture'+(reanalyze?'/analyze':''),{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body),signal:ctrl.signal});const raw=await response.text();if(raw.length>131072)throw Error('OUTPUT_LIMIT');const x=JSON.parse(raw);if(!response.ok)throw Error(x.code);if(ticket!==generation.current||ctrl.signal.aborted)return;
 if(reanalyze){const next=reanalysisResult.parse(x.result);if(next.artifactId!==result!.id||next.sha256!==result!.sha256||next.deploymentId!==deploymentId)throw Error('ASSOCIATION_CONFLICT');setAnalysis(next);}else{const next=captureResult.parse(x.result);if(next.deploymentId!==deploymentId)throw Error('ASSOCIATION_CONFLICT');setResult(next);}setStatus('Capture artifact available. Analysis does not establish packet completeness.');
 }catch(e){if(ticket===generation.current)setStatus(messages[e instanceof Error?e.message:'']??'Capture or analysis could not complete. Existing artifact, if any, is unchanged.');}finally{if(ticket===generation.current){request.current=null;setBusy(false);}}}
 const shown=analysis??result;
 return <section aria-label="Link capture settings"><label>PCAP filename<input value={filename} onChange={e=>setFilename(e.target.value)} maxLength={128}/></label><label>Duration (seconds)<input type="number" min={1} max={10} value={duration} onChange={e=>setDuration(Number(e.target.value))}/></label><label>Snapshot length (bytes)<input type="number" min={64} max={65535} value={snaplen} onChange={e=>setSnaplen(Number(e.target.value))}/></label><label>Capture filter<input value={filter} onChange={e=>setFilter(e.target.value)} maxLength={1024}/></label><label>TShark display filter<input value={display} onChange={e=>setDisplay(e.target.value)} maxLength={1024}/></label><label>Reviewed Lua<select value={lua?'reviewed':'none'} onChange={e=>setLua(e.target.value==='reviewed')}><option value="none">None</option><option value="reviewed">{reviewedLua.label}</option></select></label><button disabled={!ready||busy} onClick={()=>void run()}>Start capture</button><button disabled={!busy} onClick={cancel}>Cancel capture</button><p role="status">{status}</p><p>One PCAP, maximum 1 MiB, retained in application memory for 5 minutes. No automatic rotation or persistent file storage.</p>{result&&<><p>{result.filename} · {result.bytes} bytes</p>{available?<a href={`/api/live/capture/${result.id}/download`} download={result.filename}>Save PCAP</a>:<p>Artifact expired or deployment unavailable.</p>}<button disabled={!available||busy} onClick={()=>void run(true)}>Reanalyze same PCAP</button></>}{shown&&<><p>Analysis: {shown.analysis} · first {shown.packets.length} displayed packets</p><div style={{overflowX:'auto'}}><table><thead><tr><th>Frame</th><th>Bytes</th><th>Protocol</th></tr></thead><tbody>{shown.packets.map(p=><tr key={p.number}><td>{p.number}</td><td>{p.bytes}</td><td>{p.protocol}</td></tr>)}</tbody></table></div></>}</section>;
}
