import {Capture} from './Capture';
import React,{useEffect,useState,useCallback} from 'react';
import {createRoot} from 'react-dom/client';
import {Canvas} from '../web/src/workbench/Canvas';
import {NodeLogs} from '../web/src/workbench/NodeLogs';
import type {MultiObservation} from '../../contracts/multi-observation';
import {parseLiveGraph,type LiveGraph} from '../../contracts/live-graph';
import '@xyflow/react/dist/style.css';
import '../web/src/workbench/workbench.css';
import './style.css';
type Snapshot={details:MultiObservation|null;loadError:string|null;project:{entry:string;revision:string;files:{path:string}[]};graph:LiveGraph|null;lifecycle:{phase:string;deploymentId:string|null;reason:string|null};observation:{observedAt:string;states:Record<string,string>;reason:string|null}|null};
function App(){
 const [snapshot,setSnapshot]=useState<Snapshot|null>(null),[connected,setConnected]=useState(false),[selected,setSelected]=useState<string|null>(null),[tab,setTab]=useState('logs'),[error,setError]=useState(''),[busy,setBusy]=useState(false),[search,setSearch]=useState('');
 const [now,setNow]=useState(Date.now());useEffect(()=>{const timer=setInterval(()=>setNow(Date.now()),1000);return()=>clearInterval(timer);},[]);
 const stale=Boolean(snapshot?.observation&&now-Date.parse(snapshot.observation.observedAt)>15000);
 const choose=useCallback((id:string|null)=>setSelected(id),[]);
 useEffect(()=>{const events=new EventSource('/api/live/events');events.addEventListener('snapshot',e=>{try{if(new TextEncoder().encode(e.data).length>2200000)throw Error();const next=JSON.parse(e.data);if(next.graph)next.graph=parseLiveGraph(JSON.stringify(next.graph));setSnapshot(next);setConnected(true);}catch{setError('Invalid live response. No new data accepted.');setConnected(false);}});events.onerror=()=>setConnected(false);return()=>events.close();},[]);
 async function action(name:string){setBusy(true);setError('');try{const r=await fetch('/api/live/'+name,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(name==='go'?{revision:snapshot?.project.revision}:{})});const x=await r.json();if(!r.ok)throw Error(x.code==='RUNTIME_PREFLIGHT_FAILED'?'The owned runtime is unavailable or its identity could not be verified. Resume the configured runtime, then retry GO. No deployment was started.':x.code==='DEPLOYMENT_FAILED'?'Deployment did not complete. Resources may remain; use Stop lab for scoped cleanup before retrying.':x.code??'Operation failed');}catch(e){setError(e instanceof Error?e.message:'Operation failed');}finally{setBusy(false);}}
 const g=snapshot?.graph,node=g?.nodes.find(n=>n.id===selected),link=g?.links.find(l=>l.id===selected),phase=snapshot?.lifecycle.phase;
 return <main className="live-app"><header><div><strong>Containerlab</strong><span>{snapshot?.project.entry??'Opening project…'}</span></div><div><span role="status">{connected?(phase==='ready'?'Not deployed':phase):'Disconnected · updates unavailable'}</span><button disabled={busy||!connected||!g||g.status!=='declarations_only'||!['ready','stopped'].includes(phase??'')} onClick={()=>void action('go')}>GO</button><button disabled={busy||!connected||!['running','partial','failed','disconnected'].includes(phase??'')} onClick={()=>void action('stop')}>Stop lab</button></div></header>
 {snapshot?.loadError&&<p role="alert" className="live-error">{snapshot.loadError}</p>}{error&&<p className="live-error" role="alert">{error}</p>}<div className="live-workspace"><nav aria-label="Project"><h2>Project</h2><p>{snapshot?.project.entry}</p><details><summary>Included files</summary><ul>{snapshot?.project.files.map(f=><li key={f.path}>{f.path}</li>)}</ul></details><label>Find a node<input type="search" value={search} onChange={e=>setSearch(e.target.value)} maxLength={256}/></label><ul className="live-node-list">{g?.nodes.filter(n=>n.name.toLowerCase().includes(search.toLowerCase())).map(n=><li key={n.id}><button onClick={()=>choose(n.id)} aria-pressed={selected===n.id}>{n.name}<small>{n.kind}</small></button></li>)}</ul><p>Containerlab loads and deploys the selected project.</p></nav>
 <section className="live-center"><div className="live-freshness">{snapshot?.observation?.reason||stale?'Runtime observation unavailable or stale':snapshot?.observation?`Last runtime observation: ${snapshot.observation.observedAt}`:'No runtime observations yet.'} Container state does not establish application health.</div>{g?<Canvas g={g} selected={selected} choose={choose} states={connected&&!stale&&!snapshot?.observation?.reason?snapshot?.observation?.states??{}:{}}/>:<div className="live-empty">Waiting for native topology loading.</div>}{g?.diagnostics.map((d,i)=><p key={i} role="status">{d.message}</p>)}
 <section className="live-output" aria-label="Node output">{['ready','stopped'].includes(phase??'')&&<p>Use GO to start this lab before viewing live node output.</p>}<h2>Node output{node?' · '+node.name:''}</h2><div role="tablist" aria-label="Node output type"><button role="tab" aria-selected={tab==='logs'} onClick={()=>setTab('logs')}>Logs</button><button role="tab" aria-selected={tab==='serial'} onClick={()=>setTab('serial')}>Serial console</button></div>{!node?<p>Select a node to view its output.</p>:tab==='logs'?<NodeLogs key={`${node.id}:${snapshot?.lifecycle.deploymentId}:${connected}:${stale}:${phase}`} nodeId={node.id} name={node.name} deploymentId={connected&&!stale&&phase==='running'?snapshot?.lifecycle.deploymentId??null:null} source={g!.provenance.sourceSha256} bundle={g!.provenance.bundleSha256} onInvalidated={setError}/>:<div><button disabled>Connect serial</button><button disabled>Disconnect</button><p>No qualified serial endpoint is available for this node in this runtime. Container logs remain available separately.</p><pre>No serial connection.</pre></div>}</section></section>
 <aside aria-label="Selected object"><h2>{node?'Node details':link?'Link capture':'Inspector'}</h2>{node?<><h3>{node.name}</h3><p>Native kind: {node.kind??'Unresolved'}</p><p>Runtime: {connected?snapshot?.observation?.states[node.id]??'Not observed':'Unavailable'}</p><h3>Interfaces</h3>{snapshot?.details?.endpoints.filter(e=>e.nodeId===node.id).map(e=><p key={e.endpointId}>{e.declaredInterface}: {connected&&!stale&&!snapshot?.observation?.reason?`${e.status} · admin ${e.administrativeState} · carrier ${e.carrier}`:'Observation unavailable'}</p>)}<p>Logs and serial output appear beneath the topology.</p></>:link?<><p>Link {link.occurrence+1} · {link.type}</p>{['ready','stopped'].includes(phase??'')&&<p>Use GO to start this lab before capturing traffic.</p>}<Capture key={`${link.id}:${snapshot?.lifecycle.deploymentId}:${connected}:${phase}`} linkId={link.id} deploymentId={snapshot?.lifecycle.deploymentId??null} ready={connected&&!stale&&phase==='running'}/></>:<p>Select a node or link.</p>}</aside></div></main>;
}
createRoot(document.getElementById('root')!).render(<App/>);
