import React,{useEffect,useMemo,useRef,useState}from'react';
import{ReactFlow,Background,MiniMap,Controls,Handle,Position,useNodesState,type Node,type NodeProps,type ReactFlowInstance,type Viewport}from'@xyflow/react';
import type{LiveGraph}from'../../../../contracts/live-graph.ts';
import{presentation,type Card}from'./model';
type Data={card:Card;choose:(id:string)=>void;state:string;[key:string]:unknown};
function Device({data,selected}:NodeProps<Node<Data>>){const c=data.card;return <div className={`wb-device ${selected?'chosen':''} ${c.boundary?'boundary':''}`} style={{height:c.height}}><button className="wb-device-title nodrag" onClick={()=>data.choose(c.selectId)} aria-label={`Select ${c.name}`}><span className="wb-device-icon" aria-hidden="true">{c.boundary?'◇':'▤'}</span><span><strong>{c.name}</strong><small>{c.kind}</small></span></button><span className="wb-device-state">{data.state}</span>{c.ports.map((p,i)=><div className={`wb-port ${p.side}`} style={{top:61+i*25}} key={p.id}><Handle id={p.id} type={p.position===0?'source':'target'} position={p.side==='left'?Position.Left:Position.Right} isConnectable={false}/><button className="nodrag" onClick={e=>{e.stopPropagation();data.choose(p.linkId);}} aria-label={`Inspect ${c.name} ${p.name}`}>{p.name}</button></div>)}</div>}
const nodeTypes={device:Device};
export function Canvas({g,selected,choose,states}:{g:LiveGraph;selected:string|null;choose:(id:string|null)=>void;states:Record<string,string>}){
 const model=useMemo(()=>presentation(g),[g.revision]);const [nodes,setNodes,onNodesChange]=useNodesState<Node<Data>>([]);const [flow,setFlow]=useState<ReactFlowInstance<Node<Data>>|null>(null);const [notice,setNotice]=useState('');const container=useRef<HTMLDivElement>(null);
 const key=`clab-view:${g.provenance.bundleSha256}:${g.provenance.sourceSha256}:${g.revision}`;
 const base=()=>model.cards.map(c=>({id:c.id,type:'device',position:c.position,data:{card:c,choose,state:states[c.id]??(c.boundary?'Boundary':'Not observed')}}));
 function save(viewport?:Viewport){try{const positions=Object.fromEntries((flow?.getNodes()??nodes).map(n=>[n.id,n.position]));const value=JSON.stringify({width:container.current?.clientWidth,positions,viewport:viewport??flow?.getViewport()});if(value.length<=32768)localStorage.setItem(key,value);}catch{setNotice('View preferences unavailable; layout still works.');}}
 useEffect(()=>{let initial=base();let viewport:Viewport|undefined;try{const raw=localStorage.getItem(key);if(raw&&raw.length<=32768){const p=JSON.parse(raw);if(p.positions&&Object.keys(p.positions).length===initial.length&&initial.every(n=>{const a=p.positions[n.id];return a&&Number.isFinite(a.x)&&Number.isFinite(a.y)&&Math.abs(a.x)<100000&&Math.abs(a.y)<100000;})){initial=initial.map(n=>({...n,position:p.positions[n.id]}));const v=p.viewport;if(v&&typeof p.width==='number'&&Math.abs(p.width-(container.current?.clientWidth??p.width))<p.width*.2&&[v.x,v.y,v.zoom].every(Number.isFinite)&&v.zoom>=0.1&&v.zoom<=2)viewport=v;}}}catch{setNotice('Saved view unavailable; using default layout.');}setNodes(initial);if(flow){const t=setTimeout(()=>{if(viewport)void flow.setViewport(viewport);else void flow.fitView({padding:0.12});},30);return()=>clearTimeout(t);}},[key,flow]);
 useEffect(()=>{setNodes(ns=>ns.map(n=>({...n,selected:selected===n.data.card.selectId,data:{...n.data,choose,state:states[n.id]??(n.data.card.boundary?'Boundary':'Not observed')}})));},[selected,states,choose]);
 useEffect(()=>{const el=container.current;if(!el||!flow)return;let width=el.clientWidth;const observer=new ResizeObserver(()=>{const next=el.clientWidth;if(width&&Math.abs(next-width)>width*.2)void flow.fitView({padding:0.12});width=next;});observer.observe(el);return()=>observer.disconnect();},[flow]);
 const edges=model.wires.map(w=>({...w,type:'smoothstep',label:selected===w.id?w.label:undefined,selected:selected===w.id,style:{stroke:selected===w.id?'#087f8c':'#78909e',strokeWidth:selected===w.id?3:1.5,strokeDasharray:w.stub?'5 4':undefined},labelStyle:{fontSize:11},interactionWidth:24}));
 return <div className="wb-canvas-wrap"><div className="wb-canvas-toolbar"><span>Drag to arrange · select an interface or link</span><button onClick={()=>void flow?.fitView({padding:0.12})}>Fit view</button><button onClick={()=>{try{localStorage.removeItem(key);}catch{}setNodes(base());setTimeout(()=>void flow?.fitView({padding:0.12}),30);}}>Reset layout</button></div><div ref={container} className="wb-canvas" aria-label="Lab topology canvas"><ReactFlow nodes={nodes} edges={edges} nodeTypes={nodeTypes} onNodesChange={onNodesChange} onInit={setFlow} onNodeClick={(_,n)=>choose(n.data.card.selectId)} onEdgeClick={(_,e)=>choose(e.id)} onPaneClick={()=>choose(null)} nodesConnectable={false} edgesReconnectable={false} deleteKeyCode={null} onNodeDragStop={()=>save()} onMoveEnd={(_,v)=>save(v)} minZoom={0.1} maxZoom={2} fitView><Background color="#cbd5df" gap={22}/><Controls showInteractive={false}/><MiniMap pannable zoomable nodeColor="#a1bbc6"/></ReactFlow></div>{notice&&<p className="wb-notice">{notice}</p>}<div className="wb-legend">● Declared node <span>◇ Boundary / unresolved reference</span><span>Lines represent connections, not traffic</span></div></div>
}
