import{Reanalysis}from'./Reanalysis';
import React,{useEffect,useRef,useState}from'react';
import{captureRequest,captureResult,reviewedLua,type CaptureResult,type ReanalysisResult}from'../../../../contracts/capture.ts';
const messages:Record<string,string>={LUA_NOT_QUALIFIED:'Reviewed Lua is not qualified for this session.',LUA_INTEGRITY:'Reviewed analysis files changed; execution refused.',CAPTURE_NOT_QUALIFIED:'Capture worker not qualified for this session.',CAPTURE_UNSUPPORTED:'This endpoint capture profile is unsupported.',CAPTURE_UNAVAILABLE:'Capture endpoint unavailable.',CAPTURE_FAILED:'Capture failed; check the BPF filter and endpoint availability.',CAPTURE_TIMEOUT:'Capture exceeded its deadline.',ASSOCIATION_CONFLICT:'Capture identity changed; no artifact accepted.',CANCELLED:'Capture cancelled.',BUSY:'Another capture is running.',OUTPUT_LIMIT:'Capture output limit exceeded.',OBSERVATION_UNAVAILABLE:'Runtime session unavailable.'};
export function CaptureRun({deploymentId,endpointId,filename,duration,snaplen,captureFilter,displayFilter,luaEnabled,luaId,luaArgs,onInvalidated}:{deploymentId:string|null;endpointId:string;filename:string;duration:string;snaplen:string;captureFilter:string;displayFilter:string;luaEnabled:boolean;luaId:string;luaArgs:string;onInvalidated:(s:string)=>void}){
 const[analysis,setAnalysis]=useState<ReanalysisResult|null>(null),[reanalysisAllowed,setReanalysisAllowed]=useState(false),[reanalyzing,setReanalyzing]=useState(false),[initialFilter,setInitialFilter]=useState('');
 const[luaAllowed,setLuaAllowed]=useState(false);
 const[allowed,setAllowed]=useState<string[]>([]),[message,setMessage]=useState('Capture worker unavailable.'),[busy,setBusy]=useState(false),[result,setResult]=useState<CaptureResult|null>(null),[expired,setExpired]=useState(false);
 const active=useRef<AbortController|null>(null),generation=useRef(0),job=useRef('');
 useEffect(()=>{const c=new AbortController();if(deploymentId)void fetch('/api/capture/config',{signal:c.signal}).then(r=>r.json()).then(x=>{if(!c.signal.aborted&&x.deploymentId===deploymentId&&Array.isArray(x.endpoints)){setAllowed(x.endpoints);setReanalysisAllowed(x.reanalysis===true);setLuaAllowed(Array.isArray(x.luaProfiles)&&x.luaProfiles.some((p:any)=>p.id===reviewedLua.id&&p.sha256===reviewedLua.sha256));setMessage('Qualified Linux veth capture profile.');}}).catch(()=>{});return()=>{c.abort();generation.current++;active.current?.abort();if(active.current)void fetch('/api/capture/cancel',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({jobId:job.current})}).catch(()=>{});};},[deploymentId]);
 useEffect(()=>{if(!result)return;const t=setInterval(()=>setExpired(Date.now()>=Date.parse(result.expiresAt)),1000);return()=>clearInterval(t);},[result]);
 const valid=captureRequest.safeParse({jobId:'0'.repeat(32),deploymentId,endpointId,filename,duration:Number(duration),snaplen:Number(snaplen),captureFilter,displayFilter,...(luaEnabled?{luaId}: {})});
 function stop(){generation.current++;active.current?.abort();active.current=null;setBusy(false);setResult(null);setMessage('Capture cancelled; no artifact retained.');void fetch('/api/capture/cancel',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({jobId:job.current})}).catch(()=>{});}
 async function start(){if(!valid.success)return;const c=new AbortController(),t=++generation.current;active.current=c;job.current=crypto.randomUUID().replaceAll('-','');setBusy(true);setResult(null);setAnalysis(null);setInitialFilter(valid.data.displayFilter);setMessage('Capturing and analyzing…');const timer=setTimeout(()=>c.abort(),45000);
 try{const r=await fetch('/api/capture',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...valid.data,jobId:job.current}),signal:c.signal});const text=await r.text();if(text.length>65536)throw Error('OUTPUT_LIMIT');const x=JSON.parse(text);if(t!==generation.current||c.signal.aborted)return;if(!r.ok)throw Error(messages[x.code]?x.code:'CAPTURE_FAILED');const value=captureResult.parse(x.capture);if(value.id!==job.current||value.deploymentId!==deploymentId||value.endpointId!==endpointId||(luaEnabled&&(value.lua?.id!==luaId||value.lua?.sha256!==reviewedLua.sha256)))throw Error('ASSOCIATION_CONFLICT');setResult(value);setExpired(false);setMessage('Capture artifact ready. Completeness is not established.');
 }catch(e){if(t!==generation.current)return;const code=e instanceof Error?e.message:'';setMessage(c.signal.aborted?'Capture cancelled or timed out.':messages[code]??'Capture response invalid.');if(['ASSOCIATION_CONFLICT','OBSERVATION_UNAVAILABLE'].includes(code))onInvalidated(messages[code]);}finally{clearTimeout(timer);if(t===generation.current){active.current=null;setBusy(false);}}}
 const view=analysis??result;
 const capable=!!deploymentId&&allowed.includes(endpointId);
 return <><p role="status">{message}</p><p className="wb-help">First qualified profile: Linux veth, 1–10 seconds, fixed 1 MiB cap. Artifact retained in memory for 5 minutes. Analysis examines at most the first 100 frames; no payload fields. Reviewed Lua requires a qualified session, exact listed ID and no arguments.</p><button disabled={!capable||!valid.success||(luaEnabled&&(!luaAllowed||luaArgs.length>0))||busy||reanalyzing} onClick={()=>void start()}>{capable?'Start capture':'Start capture — unavailable'}</button>{busy&&<button onClick={stop}>Cancel capture</button>}{result&&<section aria-label="Capture result"><p>{result.bytes} bytes · {result.limited?'Byte limit reached':'Duration completed'} · SHA-256 {result.sha256}</p>{view?.lua&&<p>Reviewed Lua: {view.lua.id} · SHA-256 {view.lua.sha256}</p>}<p>Displayed filter: {(analysis?.displayFilter??initialFilter)||'None'}</p>{analysis&&<p>Reanalyzed: {analysis.analyzedAt} · Captured: {result.createdAt}</p>}<p>Analysis: {view?.analysis==='complete'?'Complete within first-100-frame limit':'Unavailable; check the display filter or analysis worker.'}</p>{expired?<p>Artifact expired. Capture again to obtain a new file.</p>:<a href={`/api/capture/${result.id}/download`} download={result.filename}>Download {result.filename}</a>}<Reanalysis key={result.id} capture={result} qualified={reanalysisAllowed} expired={expired} displayFilter={displayFilter} luaEnabled={luaEnabled} luaId={luaId} luaArgs={luaArgs} luaAllowed={luaAllowed} onBusy={setReanalyzing} onResult={setAnalysis} onInvalidated={onInvalidated}/><table><caption>Packet metadata · {(view?.packets.length??0)} matching frames</caption><thead><tr><th>Frame</th><th>Seconds</th><th>Bytes</th><th>Source</th><th>Destination</th><th>Protocol</th></tr></thead><tbody>{view?.packets.map(p=><tr key={p.number}><td>{p.number}</td><td>{p.seconds}</td><td>{p.bytes}</td><td>{p.source}</td><td>{p.destination}</td><td>{p.protocol}</td></tr>)}</tbody></table></section>}</>;
}
