import React,{useEffect,useRef,useState}from'react';
import{captureRequest,captureResult,type CaptureResult}from'../../../../contracts/capture.ts';
const messages:Record<string,string>={CAPTURE_NOT_QUALIFIED:'Capture worker not qualified for this session.',CAPTURE_UNSUPPORTED:'This endpoint capture profile is unsupported.',CAPTURE_UNAVAILABLE:'Capture endpoint unavailable.',CAPTURE_FAILED:'Capture failed; check the BPF filter and endpoint availability.',CAPTURE_TIMEOUT:'Capture exceeded its deadline.',ASSOCIATION_CONFLICT:'Capture identity changed; no artifact accepted.',CANCELLED:'Capture cancelled.',BUSY:'Another capture is running.',OUTPUT_LIMIT:'Capture output limit exceeded.',OBSERVATION_UNAVAILABLE:'Runtime session unavailable.'};
export function CaptureRun({deploymentId,endpointId,filename,duration,snaplen,captureFilter,displayFilter,luaEnabled,onInvalidated}:{deploymentId:string|null;endpointId:string;filename:string;duration:string;snaplen:string;captureFilter:string;displayFilter:string;luaEnabled:boolean;onInvalidated:(s:string)=>void}){
 const[allowed,setAllowed]=useState<string[]>([]),[message,setMessage]=useState('Capture worker unavailable.'),[busy,setBusy]=useState(false),[result,setResult]=useState<CaptureResult|null>(null),[expired,setExpired]=useState(false);
 const active=useRef<AbortController|null>(null),generation=useRef(0),job=useRef('');
 useEffect(()=>{const c=new AbortController();if(deploymentId)void fetch('/api/capture/config',{signal:c.signal}).then(r=>r.json()).then(x=>{if(!c.signal.aborted&&x.deploymentId===deploymentId&&Array.isArray(x.endpoints)){setAllowed(x.endpoints);setMessage('Qualified Linux veth capture profile.');}}).catch(()=>{});return()=>{c.abort();generation.current++;active.current?.abort();if(active.current)void fetch('/api/capture/cancel',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({jobId:job.current})}).catch(()=>{});};},[deploymentId]);
 useEffect(()=>{if(!result)return;const t=setInterval(()=>setExpired(Date.now()>=Date.parse(result.expiresAt)),1000);return()=>clearInterval(t);},[result]);
 const valid=captureRequest.safeParse({jobId:'0'.repeat(32),deploymentId,endpointId,filename,duration:Number(duration),snaplen:Number(snaplen),captureFilter,displayFilter});
 function stop(){generation.current++;active.current?.abort();active.current=null;setBusy(false);setResult(null);setMessage('Capture cancelled; no artifact retained.');void fetch('/api/capture/cancel',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({jobId:job.current})}).catch(()=>{});}
 async function start(){if(!valid.success)return;const c=new AbortController(),t=++generation.current;active.current=c;job.current=crypto.randomUUID().replaceAll('-','');setBusy(true);setResult(null);setMessage('Capturing and analyzing…');const timer=setTimeout(()=>c.abort(),45000);
 try{const r=await fetch('/api/capture',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...valid.data,jobId:job.current}),signal:c.signal});const text=await r.text();if(text.length>65536)throw Error('OUTPUT_LIMIT');const x=JSON.parse(text);if(t!==generation.current||c.signal.aborted)return;if(!r.ok)throw Error(messages[x.code]?x.code:'CAPTURE_FAILED');const value=captureResult.parse(x.capture);if(value.id!==job.current||value.deploymentId!==deploymentId||value.endpointId!==endpointId)throw Error('ASSOCIATION_CONFLICT');setResult(value);setExpired(false);setMessage('Capture artifact ready. Completeness is not established.');
 }catch(e){if(t!==generation.current)return;const code=e instanceof Error?e.message:'';setMessage(c.signal.aborted?'Capture cancelled or timed out.':messages[code]??'Capture response invalid.');if(['ASSOCIATION_CONFLICT','OBSERVATION_UNAVAILABLE'].includes(code))onInvalidated(messages[code]);}finally{clearTimeout(timer);if(t===generation.current){active.current=null;setBusy(false);}}}
 const capable=!!deploymentId&&allowed.includes(endpointId);
 return <><p role="status">{message}</p><p className="wb-help">First qualified profile: Linux veth, 1–10 seconds, fixed 1 MiB cap. Artifact retained in memory for 5 minutes. Analysis examines at most the first 100 frames; no payload fields. Lua execution remains unavailable.</p><button disabled={!capable||!valid.success||luaEnabled||busy} onClick={()=>void start()}>{capable?'Start capture':'Start capture — unavailable'}</button>{busy&&<button onClick={stop}>Cancel capture</button>}{result&&<section aria-label="Capture result"><p>{result.bytes} bytes · {result.limited?'Byte limit reached':'Duration completed'} · SHA-256 {result.sha256}</p><p>Analysis: {result.analysis==='complete'?'Complete within first-100-frame limit':'Unavailable; check the display filter or analysis worker.'}</p>{expired?<p>Artifact expired. Capture again to obtain a new file.</p>:<a href={`/api/capture/${result.id}/download`} download={result.filename}>Download {result.filename}</a>}<table><caption>Packet metadata · {result.packets.length} matching frames</caption><thead><tr><th>Frame</th><th>Seconds</th><th>Bytes</th><th>Source</th><th>Destination</th><th>Protocol</th></tr></thead><tbody>{result.packets.map(p=><tr key={p.number}><td>{p.number}</td><td>{p.seconds}</td><td>{p.bytes}</td><td>{p.source}</td><td>{p.destination}</td><td>{p.protocol}</td></tr>)}</tbody></table></section>}</>;
}
