import React,{useEffect,useRef,useState}from'react';
import{logView}from'./log-view';
import{logSnapshotSchema,type LogSnapshot}from'../../../../contracts/node-logs.ts';
const reasons:Record<string,string>={INCOMPATIBLE_SESSION:'Runtime session needs fresh enrollment.',MALFORMED_LOGS:'Log response was invalid; no output accepted.',INVALID_REQUEST:'Log target is not valid for this enrollment.',LOGS_NOT_QUALIFIED:'Log access is not qualified for this session.',ASSOCIATION_CONFLICT:'Runtime identity changed. No replacement logs accepted.',NODE_UNAVAILABLE:'The enrolled node is unavailable.',LOG_SOURCE_UNSUPPORTED:'Container logs are unsupported for this node.',LOG_SOURCE_UNAVAILABLE:'The log source is unavailable.',OBSERVATION_UNAVAILABLE:'Runtime session unavailable or expired.',BUSY:'Another log read is running. Try again.',INSPECTION_TIMEOUT:'Log read timed out.',OUTPUT_LIMIT:'Log response exceeded its limit.',CANCELLED:'Log read cancelled.'};
export function NodeLogs({nodeId,name,deploymentId,source,bundle,onInvalidated}:{onInvalidated:(reason:string)=>void;nodeId:string;name:string;deploymentId:string|null;source:string;bundle:string}){
 const[snapshot,setSnapshot]=useState<LogSnapshot|null>(null),[status,setStatus]=useState('No logs loaded.'),[busy,setBusy]=useState(false),[follow,setFollow]=useState(false),[filter,setFilter]=useState(''),[tail,setTail]=useState(100);
 const request=useRef<AbortController|null>(null),generation=useRef(0);
 useEffect(()=>()=>{generation.current++;request.current?.abort();},[]);
 async function load(){if(!deploymentId||request.current)return;const c=new AbortController(),ticket=++generation.current;request.current=c;setBusy(true);setStatus('Reading logs…');const timer=setTimeout(()=>c.abort(),11000);
 try{const u=new URLSearchParams({nodeId,deploymentId});const r=await fetch('/api/node-logs?'+u,{signal:c.signal});const text=await r.text();if(ticket!==generation.current)return;if(c.signal.aborted)throw Error('CANCELLED');if(new TextEncoder().encode(text).length>150000)throw Error('OUTPUT_LIMIT');const x=JSON.parse(text);if(!r.ok)throw Error(reasons[x.code]?x.code:'LOG_SOURCE_UNAVAILABLE');const next=logSnapshotSchema.parse(x.snapshot);if(next.nodeId!==nodeId||next.deploymentId!==deploymentId||next.sourceSha256!==source||next.bundleSha256!==bundle)throw Error('ASSOCIATION_CONFLICT');if(ticket!==generation.current||c.signal.aborted)return;setSnapshot(next);setStatus(next.text?'Logs loaded.':'Log source returned no output.');
 }catch(e){if(ticket!==generation.current)return;setFollow(false);setSnapshot(null);const code=e instanceof Error?e.message:'';if(['ASSOCIATION_CONFLICT','OBSERVATION_UNAVAILABLE','INCOMPATIBLE_SESSION'].includes(code)){onInvalidated(reasons[code]);return;}setStatus(c.signal.aborted?'Log read cancelled or timed out.':reasons[e instanceof Error?e.message:'']??'Invalid log response.');}finally{clearTimeout(timer);if(ticket===generation.current){request.current=null;setBusy(false);}}}
 function stop(){generation.current++;request.current?.abort();request.current=null;setBusy(false);setFollow(false);setStatus('Stopped. Displayed output is last fetched.');}
 function clear(){stop();setSnapshot(null);setStatus('Output cleared. Load logs to fetch again.');}
 const visible=logView(snapshot?.text??'',tail,filter);
 useEffect(()=>{if(!follow||busy)return;const t=setTimeout(()=>void load(),2000);return()=>clearTimeout(t);},[follow,busy,snapshot]);
 return <section aria-label="Selected node logs"><h3>Node logs</h3><p>{name}</p><p className="wb-small">Container stdout/stderr · latest100 lines ·64KiB maximum. Follow refreshes the tail every2 seconds; gaps are possible.</p><p role="status">{deploymentId?status:'Connect a matching enrolled runtime to read logs.'}</p><button disabled={!deploymentId||busy} onClick={()=>void load()}>Load logs</button><label><input type="checkbox" disabled={!deploymentId} checked={follow} onChange={e=>{if(e.target.checked){setFollow(true);void load();}else stop();}}/> Follow logs</label><button disabled={!busy&&!follow} onClick={stop}>Stop logs</button><button disabled={!snapshot&&!busy&&!follow} onClick={clear}>Clear log output</button><label>Display tail<select aria-label="Display log tail" value={tail} onChange={e=>setTail(Number(e.target.value))}><option value={25}>Last 25 fetched lines</option><option value={50}>Last 50 fetched lines</option><option value={100}>Last 100 fetched lines</option></select></label><label>Filter fetched lines<input aria-label="Filter fetched log lines" type="search" maxLength={256} value={filter} onChange={e=>setFilter(e.target.value)}/></label><p className="wb-small">Literal, case-insensitive filter applied after tail selection. Only filters fetched text; it does not search older logs.</p>{snapshot&&<p role="status">Showing {visible.matched} of {visible.window} selected lines ({visible.fetched} fetched).{!snapshot.text?" Log source returned no output.":visible.matched===0?" No fetched lines match this filter.":""}</p>}{snapshot?.truncated&&<p role="status">Output truncated at the byte limit.</p>}<pre className="wb-log-output" aria-label="Node log output" tabIndex={0}>{snapshot?visible.text:'No logs loaded for this node.'}</pre>{snapshot&&<p className="wb-small">Last fetched {snapshot.observedAt}</p>}<p className="wb-help">Log text is untrusted and may contain sensitive application data. Output stays in this view; it is not persisted or interpreted as terminal commands. Empty logs do not establish application health.</p></section>;
}
