import React,{useEffect,useRef,useState}from'react';
import{reanalysisRequest,reanalysisResult,reviewedLua,type CaptureResult,type ReanalysisResult}from'../../../../contracts/capture.ts';
export function Reanalysis({capture,qualified,expired,displayFilter,luaEnabled,luaId,luaArgs,luaAllowed,onBusy,onResult,onInvalidated}:{capture:CaptureResult;qualified:boolean;expired:boolean;displayFilter:string;luaEnabled:boolean;luaId:string;luaArgs:string;luaAllowed:boolean;onBusy:(b:boolean)=>void;onResult:(r:ReanalysisResult)=>void;onInvalidated:(s:string)=>void}){
 const[busy,setBusy]=useState(false),[message,setMessage]=useState('');const active=useRef<AbortController|null>(null),job=useRef(''),generation=useRef(0);
 const request=reanalysisRequest.safeParse({jobId:'0'.repeat(32)===capture.id?'1'.repeat(32):'0'.repeat(32),artifactId:capture.id,sha256:capture.sha256,displayFilter,...(luaEnabled?{luaId}:{})});
 function cancel(){generation.current++;active.current?.abort();active.current=null;setBusy(false);onBusy(false);setMessage('Reanalysis cancelled. The original artifact retains its existing expiry.');void fetch('/api/capture/cancel',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({jobId:job.current})}).catch(()=>{});}
 useEffect(()=>()=>{generation.current++;if(active.current){active.current.abort();void fetch('/api/capture/cancel',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({jobId:job.current})}).catch(()=>{});}onBusy(false);},[capture.id]);
 useEffect(()=>{if(expired&&active.current)cancel();},[expired]);
 async function run(){if(!request.success)return;const c=new AbortController(),token=++generation.current;active.current=c;job.current=crypto.randomUUID().replaceAll('-','');setBusy(true);onBusy(true);setMessage('Reanalyzing the same captured bytes…');const timer=setTimeout(()=>c.abort(),25000);
 try{
  const response=await fetch('/api/capture/reanalyze',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...request.data,jobId:job.current}),signal:c.signal});const text=await response.text();if(text.length>65536)throw Error('OUTPUT_LIMIT');const raw=JSON.parse(text);if(token!==generation.current||c.signal.aborted)return;
  if(!response.ok)throw Error(typeof raw.code==='string'?raw.code:'ANALYSIS_UNAVAILABLE');const x=reanalysisResult.parse(raw.analysis);
  if(x.jobId!==job.current||x.artifactId!==capture.id||x.sha256!==capture.sha256||x.deploymentId!==capture.deploymentId||x.endpointId!==capture.endpointId||x.capturedAt!==capture.createdAt||x.expiresAt!==capture.expiresAt||x.displayFilter!==request.data.displayFilter||(luaEnabled?x.lua?.id!==luaId||x.lua?.sha256!==reviewedLua.sha256:x.lua!==undefined))throw Error('ARTIFACT_MISMATCH');
  if(Date.now()>=Date.parse(capture.expiresAt))throw Error('ARTIFACT_UNAVAILABLE');onResult(x);setMessage(x.analysis==='complete'?'Reanalysis complete. No new capture; original expiry unchanged.':'Analysis unavailable. The valid original PCAP remains downloadable until expiry.');
 }catch(e){if(token!==generation.current)return;const code=e instanceof Error?e.message:'';const messages:Record<string,string>={ARTIFACT_UNAVAILABLE:'Artifact expired or session changed. Capture again.',ARTIFACT_MISMATCH:'Artifact identity mismatch; analysis refused.',LUA_INTEGRITY:'Reviewed script integrity check failed.',LUA_NOT_QUALIFIED:'Reviewed Lua is unavailable for this session.',REANALYSIS_NOT_QUALIFIED:'Reanalysis is not qualified for this session.',BUSY:'Another capture or analysis is active.',OUTPUT_LIMIT:'Analysis output exceeded its limit.',CAPTURE_TIMEOUT:'Analysis exceeded its deadline.',OBSERVATION_UNAVAILABLE:'Runtime session unavailable.'};setMessage(c.signal.aborted?'Reanalysis cancelled or timed out; the original expiry is unchanged.':messages[code]??'Analysis failed. Previous displayed analysis is unchanged.');if(['ARTIFACT_MISMATCH','OBSERVATION_UNAVAILABLE'].includes(code))onInvalidated(messages[code]);
 }finally{clearTimeout(timer);if(token===generation.current){active.current=null;setBusy(false);onBusy(false);}}
 }
 return <section aria-label="Reanalysis controls"><p className="wb-help">Reanalyze this PCAP with the current display filter and reviewed Lua choice. BPF, duration, snapshot length and filename affect new captures only. No expiry extension.</p><button disabled={!qualified||expired||busy||!request.success||(luaEnabled&&(!luaAllowed||luaArgs.length>0))} onClick={()=>void run()}>{qualified?'Reanalyze current PCAP':'Reanalysis — unavailable'}</button>{busy&&<button onClick={cancel}>Cancel reanalysis</button>}<p role="status">{message}</p></section>;
}
