import React,{useEffect,useMemo,useRef,useState}from'react';
import{parseLiveGraph,type LiveGraph}from'../../../../contracts/live-graph.ts';
import{parseCurrentObservation}from'../../../../contracts/observation.ts';
import type{MultiObservation}from'../../../../contracts/multi-observation.ts';
import{NodeLogs}from'./NodeLogs';
import{CaptureSettings}from'./CaptureSettings';
import recordings from'../generated/workbench-recordings.json';
import{Canvas}from'./Canvas';import{linkName,sameSource}from'./model';import'./workbench.css';
type Bundle={sourceSha256?:string;id:string;displayName?:string;entryFile:string;fileCount:number;bundleSha256:string;companionInventory?:{name:string;sha256:string}[]};
const errors:Record<string,string>={ASSOCIATION_CONFLICT:'Identity conflict. Replacement resources were not associated.',OBSERVATION_UNAVAILABLE:'No active enrolled runtime session.',INCOMPATIBLE_SESSION:'This session needs fresh enrollment.',INSPECTION_FAILED:'Refresh failed. Current state is unavailable.',INSPECTION_TIMEOUT:'Inspection timed out.',OUTPUT_LIMIT:'Observation exceeded its limit.',BUSY:'An inspection is already running.',RATE_LIMIT:'Please wait before refreshing.'};
function Facts({items}:{items:[string,React.ReactNode][]}){return <dl className="wb-facts">{items.map(([k,v])=><React.Fragment key={k}><dt>{k}</dt><dd>{v??'Unavailable'}</dd></React.Fragment>)}</dl>}
export function Workbench(){
 const [catalog,setCatalog]=useState<Bundle[]>([]),[worker,setWorker]=useState(false),[id,setId]=useState(''),[g,setGraph]=useState<LiveGraph|null>(null),[recorded,setRecorded]=useState(false),[message,setMessage]=useState('Choose a lab to begin.'),[busy,setBusy]=useState(false);
 const [selected,setSelected]=useState<string|null>(null),[search,setSearch]=useState(''),[kind,setKind]=useState(''),[view,setView]=useState<'topology'|'table'>('topology'),[tab,setTab]=useState('Overview');
 const [snapshot,setSnapshot]=useState<MultiObservation|null>(null),[runtime,setRuntime]=useState('No runtime session connected'),[inspecting,setInspecting]=useState(false),[poll,setPoll]=useState(false),[binding,setBinding]=useState<string|null>(null),[now,setNow]=useState(Date.now());
 const loadJob=useRef<{id:string;ctrl:AbortController}|null>(null),observation=useRef<AbortController|null>(null),connection=useRef<AbortController|null>(null),ticket=useRef(0),lastTime=useRef(0);
 useEffect(()=>{const c=new AbortController();void fetch('/api/native/catalog',{signal:c.signal}).then(r=>r.json()).then(x=>{setCatalog(x.bundles);setWorker(x.available);}).catch(()=>setMessage('Catalog unavailable. Recorded examples remain available.'));const t=setInterval(()=>setNow(Date.now()),1000);return()=>{c.abort();clearInterval(t);loadJob.current?.ctrl.abort();observation.current?.abort();connection.current?.abort();};},[]);
 const choices=useMemo(()=>{const m=new Map(catalog.map(b=>[b.id,{...b,title:b.displayName??b.id}]));for(const r of recordings)m.set(r.id,{...(m.get(r.id)??{id:r.id,entryFile:r.graph.provenance.entryFile,fileCount:r.graph.provenance.fileCount,bundleSha256:r.graph.provenance.bundleSha256}),title:r.title});return [...m.values()].sort((a,b)=>a.title.localeCompare(b.title));},[catalog]);
 const bundle=choices.find(b=>b.id===id),reference=recordings.find(r=>r.id===id);
 function clearRuntime(){ticket.current++;connection.current?.abort();connection.current=null;observation.current?.abort();observation.current=null;setInspecting(false);setPoll(false);setSnapshot(null);setBinding(null);lastTime.current=0;setRuntime('No runtime session connected');}
 function accept(next:LiveGraph,isRecorded:boolean){if(!g||!sameSource(g,next)){setSelected(null);clearRuntime();}setGraph(next);setRecorded(isRecorded);setMessage(isRecorded?'Recorded declarations opened. This is not a new native load.':'Native declarations loaded.');}
 async function load(){const job={id:crypto.randomUUID().replaceAll('-',''),ctrl:new AbortController()};loadJob.current=job;setBusy(true);setMessage('Loading native declarations…');try{const r=await fetch('/api/native/load',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({bundleId:id,jobId:job.id}),signal:job.ctrl.signal});const text=await r.text();if(text.length>2200000)throw Error();const x=JSON.parse(text);if(loadJob.current!==job)return;if(!r.ok){setMessage('Native load failed; previous declarations retained. '+(typeof x.code==='string'&&/^[A-Z_]+$/.test(x.code)?x.code:'WORKER_UNAVAILABLE'));return;}const graph=parseLiveGraph(JSON.stringify(x.graph));if(graph.provenance.jobId!==job.id||graph.provenance.bundleId!==id||graph.provenance.bundleSha256!==bundle?.bundleSha256||(bundle?.sourceSha256&&graph.provenance.sourceSha256!==bundle.sourceSha256))throw Error();accept(graph,false);}catch{if(loadJob.current===job)setMessage('No new graph accepted. Native worker unavailable or response invalid.');}finally{if(loadJob.current===job){loadJob.current=null;setBusy(false);}}}
 function cancelLoad(){const job=loadJob.current;if(job){void fetch('/api/native/cancel',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({jobId:job.id})}).catch(()=>{});job.ctrl.abort();loadJob.current=null;}setBusy(false);setMessage('Loading cancelled; previous declarations retained.');}
 function disconnect(){clearRuntime();setRuntime('Runtime disconnected. Declarations retained.');}
 function invalidate(reason:string){clearRuntime();setSelected(null);setRuntime(reason+' Reconnect requires a matching enrollment.');}
 async function connect(){
  if(!g)return;clearRuntime();const generation=ticket.current,c=new AbortController();connection.current=c;setInspecting(true);setRuntime('Connecting enrolled runtime…');
  const timer=setTimeout(()=>{if(generation===ticket.current){c.abort();setRuntime('Runtime connection timed out.');}},12000);
  try{const r=await fetch('/api/observation/config',{signal:c.signal});const text=await r.text();if(text.length>2200000)throw Error('Invalid runtime configuration.');const x=JSON.parse(text);if(generation!==ticket.current||c.signal.aborted)return;if(!r.ok)throw Error(errors[x.code]??'Runtime unavailable.');const graph=parseLiveGraph(JSON.stringify(x.graph));if(!sameSource(g,graph)||!/^([a-f0-9]{64})$/.test(x.deploymentId))throw Error('Enrolled source does not match this lab. No runtime attached.');setBinding(x.deploymentId);setRuntime('Enrolled session connected · not yet observed');
  }catch(e){if(generation!==ticket.current||c.signal.aborted)return;setRuntime(e instanceof Error&&Object.values(errors).includes(e.message)?e.message:e instanceof Error&&e.message.startsWith('Enrolled source')?e.message:'Runtime unavailable or configuration invalid.');}
  finally{clearTimeout(timer);if(generation===ticket.current){connection.current=null;setInspecting(false);}}
 }
 async function refresh(){if(!g||!binding||observation.current)return;const c=new AbortController(),t=++ticket.current;observation.current=c;setInspecting(true);setRuntime('Refreshing runtime…');const timeout=setTimeout(()=>{if(t===ticket.current){c.abort();setRuntime('Inspection timed out. Previous evidence is last-known.');}},12000);try{const r=await fetch('/api/observation/snapshot',{signal:c.signal});const text=await r.text();if(text.length>262144)throw Error('Observation exceeded its limit.');const x=JSON.parse(text);if(t!==ticket.current||c.signal.aborted)return;if(!r.ok){if(['ASSOCIATION_CONFLICT','INCOMPATIBLE_SESSION','OBSERVATION_UNAVAILABLE'].includes(x.code)){invalidate(errors[x.code]);return;}throw Error(errors[x.code]??'Observation unavailable.');}const next=parseCurrentObservation(x.snapshot);if(next.contract!=='observation/0.9'||next.bundleSha256!==g.provenance.bundleSha256||next.sourceSha256!==g.provenance.sourceSha256||next.profile!==g.provenance.bundleId||next.deploymentId!==binding||next.nodes.length!==g.nodes.length||next.nodes.some(n=>!g.nodes.some(p=>p.id===n.nodeId&&p.name===n.node&&p.kind===n.kind))||next.endpoints.length!==g.links.reduce((n,l)=>n+l.endpoints.length,0)||next.endpoints.some(e=>{const p=g.links.find(l=>l.id===e.linkId)?.endpoints[e.position];return !p||p.nodeId!==e.nodeId||p.interface!==e.declaredInterface||p.nodeLabel!==e.node;})){invalidate('Observation identity mismatch. No replacement adopted.');return;}if(Date.parse(next.observedAt)>lastTime.current){lastTime.current=Date.parse(next.observedAt);setSnapshot(next);setNow(Date.now());setRuntime('Runtime observed');}else setRuntime('Older or repeated observation ignored. Previous evidence is last-known.');}catch(e){if(t===ticket.current&&!c.signal.aborted)setRuntime(e instanceof Error?e.message:'Refresh failed.');}finally{clearTimeout(timeout);if(t===ticket.current){observation.current=null;setInspecting(false);}}}
 function cancel(){ticket.current++;connection.current?.abort();connection.current=null;observation.current?.abort();observation.current=null;setInspecting(false);setPoll(false);setRuntime('Inspection cancelled. Previous evidence is last-known.');}
 useEffect(()=>{if(!poll||inspecting)return;const t=setTimeout(()=>void refresh(),5000);return()=>clearTimeout(t);},[poll,inspecting,snapshot,runtime]);
 const stale=!!snapshot&&(now-Date.parse(snapshot.observedAt)>snapshot.freshForMs||now<Date.parse(snapshot.observedAt));const lastKnown=stale||runtime!=='Runtime observed';
 const states=useMemo(()=>Object.fromEntries((snapshot?.nodes??[]).map(n=>[n.nodeId,`${n.state}${lastKnown?' · last-known':''}`])),[snapshot,lastKnown]);
 const nodes=g?.nodes.filter(n=>(!kind||n.kind===kind)&&`${n.name} ${n.kind}`.toLowerCase().includes(search.toLowerCase()))??[];
 const links=g?.links.filter(l=>linkName(l).toLowerCase().includes(search.toLowerCase())&&(!kind||l.endpoints.some(e=>g.nodes.find(n=>n.id===e.nodeId)?.kind===kind)))??[];
 const node=g?.nodes.find(n=>n.id===selected),link=g?.links.find(l=>l.id===selected);const endpoints=g?.links.flatMap(l=>l.endpoints.map((e,p)=>({l,e,p}))).filter(x=>node?x.e.nodeId===node.id:link?x.l.id===link.id:false)??[];
 const deps=g?.dependencies.filter(d=>selected===null||d.ownerId===selected)??[];
 const tabs=['Overview','Interfaces','Runtime',...(link?['Capture & TShark']:[]),...(node?['Logs','Serial console']:[]),'Dependencies','Evidence'];
 useEffect(()=>{if((!link&&tab==='Capture & TShark')||(!node&&['Logs','Serial console'].includes(tab)))setTab('Overview');},[link,node,tab]);
 return <div className="wb"><a className="wb-skip" href="#wb-content">Skip to topology</a><header className="wb-header"><a className="wb-brand" href="/">◈ <strong>containerlab</strong><span>LAB WORKBENCH</span></a><div className="wb-header-context"><strong>{bundle?.title??'Choose a lab'}</strong><span>{g?(recorded?'Recorded declarations':'Native declarations'):'No topology loaded'}</span></div><span className="wb-session">{binding?'Enrolled runtime':'Runtime not connected'}</span></header>
 <div className="wb-body"><aside className="wb-nav" aria-label="Lab and objects"><h2>Workspace</h2><label>Approved lab<select aria-label="Approved lab" value={id} disabled={busy} onChange={e=>{setId(e.target.value);setGraph(null);setSelected(null);clearRuntime();setSearch('');setKind('');setMessage('Choose how to load this lab. Previous selection and runtime cleared.');}}><option value="">Select a lab…</option>{choices.map(b=><option key={b.id} value={b.id}>{b.title}</option>)}</select></label><button className="wb-primary" disabled={!id||!worker||busy} onClick={()=>void load()}>Load native declarations</button>{busy&&<button onClick={cancelLoad}>Cancel load</button>}{reference&&<button disabled={busy} onClick={()=>accept(parseLiveGraph(JSON.stringify(reference.graph)),true)}>Open recorded topology</button>}<p className="wb-small">{worker?'Native worker available':'Native worker offline'}{reference?' · recorded example available':''}</p><hr/><label>Find an object<input type="search" placeholder="Node or interface…" value={search} onChange={e=>setSearch(e.target.value)}/></label><label>Native kind<select value={kind} onChange={e=>setKind(e.target.value)}><option value="">All kinds</option>{[...new Set(g?.nodes.map(n=>n.kind).filter(Boolean)??[])].map(k=><option key={k!}>{k}</option>)}</select></label><div className="wb-object-scroll"><h3>Nodes <span>{nodes.length} / {g?.nodes.length??0}</span></h3>{nodes.map(n=><button className="wb-object" key={n.id} aria-pressed={selected===n.id} onClick={()=>setSelected(n.id)}><span>▤ {n.name}</span><small>{n.kind??'Unknown kind'}</small></button>)}<h3>Links <span>{links.length} / {g?.links.length??0}</span></h3>{links.map(l=><button className="wb-object" key={l.id} aria-pressed={selected===l.id} onClick={()=>setSelected(l.id)}><span>{linkName(l)}</span><small>{l.type} · occurrence {l.occurrence+1}</small></button>)}</div><a className="wb-developer" href="/?view=evidence">Developer & evidence fixtures ↗</a></aside>
 <main className="wb-main" id="wb-content"><div className="wb-main-heading"><div><p className="wb-overline">READ-ONLY TOPOLOGY</p><h1>{bundle?.title??'Your lab, in one view'}</h1></div>{g&&<span className="wb-count">{g.nodes.length} nodes · {g.links.length} links</span>}</div><p className="wb-status" role="status">{message}</p>
 {g?<><div className="wb-runtime-bar"><span>{stale?'Stale · ':''}{runtime}</span><button onClick={()=>void connect()} disabled={inspecting}>Connect enrolled runtime</button><button onClick={disconnect} disabled={!binding&&!inspecting}>Disconnect runtime</button><button onClick={()=>void refresh()} disabled={!binding||inspecting}>Refresh</button>{inspecting&&<button onClick={cancel}>Cancel inspection</button>}<label><input type="checkbox" checked={poll} disabled={!binding} onChange={e=>setPoll(e.target.checked)}/> Auto refresh</label></div><div className="wb-view-tabs"><button aria-pressed={view==='topology'} onClick={()=>setView('topology')}>Topology</button><button aria-pressed={view==='table'} onClick={()=>setView('table')}>Nodes & links</button><span>{recorded?'RECORDED EXAMPLE · not a live load':'EXECUTED NATIVE LOAD'}</span></div><div className="wb-workspace"><section className="wb-primary-view">{view==='topology'?<Canvas key={`${g.provenance.bundleSha256}:${g.provenance.sourceSha256}:${g.revision}`} g={g} selected={selected} choose={setSelected} states={states}/>:<div className="wb-table-wrap"><table><caption>Semantic topology · {nodes.length} nodes / {links.length} links shown</caption><thead><tr><th>Object</th><th>Kind / type</th><th>Details</th></tr></thead><tbody>{nodes.map(n=><tr key={n.id}><td><button aria-pressed={selected===n.id} onClick={()=>setSelected(n.id)}>{n.name}</button></td><td>{n.kind}</td><td>{states[n.id]??'Not observed'}</td></tr>)}{links.map(l=><tr key={l.id}><td><button aria-pressed={selected===l.id} onClick={()=>setSelected(l.id)}>{linkName(l)}</button></td><td>{l.type}</td><td>{l.state}</td></tr>)}</tbody></table></div>}</section>
 <aside className="wb-inspector" aria-label="Selected object inspector"><p className="wb-overline">INSPECTOR</p><h2>{node?.name??(link?'Link '+(link.occurrence+1):'Lab overview')}</h2><div className="wb-inspector-tabs">{tabs.map(t=><button key={t} aria-pressed={tab===t} onClick={()=>setTab(t)}>{t}{t==='Dependencies'?` (${deps.length})`:''}</button>)}</div>
 {tab==='Overview'&&<>{node?<Facts items={[["Native kind",node.kind],["Container state",states[node.id]??'Not observed'],['Declared interfaces',endpoints.length]]}/>:link?<Facts items={[["Connection",linkName(link)],["Native type",link.type],["Declaration",link.state],['External role',link.externalRole||'None']]}/>:<><p>Select a node, interface or connection to inspect it here.</p><Facts items={[["Nodes",g.nodes.length],["Link occurrences",g.links.length],["Source",recorded?'Recorded native result':'New native execution']]}/></>}<p className="wb-help">Layout is local presentation. It does not edit configuration.</p></>}
 {tab==='Interfaces'&&<>{!selected&&<p>Select a node or link to see its interfaces.</p>}{selected&&!endpoints.length&&<p>No declared interfaces for this object.</p>}{endpoints.map(({e,l,p})=>{const o=snapshot?.endpoints.find(x=>x.linkId===l.id&&x.position===p);return <section className="wb-interface" key={`${l.id}:${p}`}><strong>{e.nodeLabel} · {e.interface||'Unspecified'}</strong><Facts items={[["Declared reference",e.referenceState],["Observed native name",o?.observedInterface??'Not observed'],['Native alias',o?.nativeAlias||'Not observed'],['Association',o?`${o.status}${lastKnown?' · last-known':''}`:'Not observed']]}/></section>})}</>}
 {tab==='Runtime'&&<><p>{stale?'Stale observation. ':''}{runtime}</p>{snapshot&&<p className="wb-small">Observed {snapshot.observedAt}</p>}{endpoints.map(({l,p,e})=>{const o=snapshot?.endpoints.find(x=>x.linkId===l.id&&x.position===p);return <section className="wb-interface" key={`${l.id}:${p}`}><strong>{e.nodeLabel}:{e.interface}</strong><Facts items={[["Operational",o?.operationalState??'Not observed'],["Administrative",o?.administrativeState??'Not observed'],["Carrier",o?.carrier??'Not observed'],["Reason",o?.reason??'No observation']]}/></section>})}<p className="wb-help">Application health and packet forwarding are not assessed. Running containers and up interfaces do not establish either.</p></>}
 {node&&tab==='Logs'&&<NodeLogs onInvalidated={invalidate} key={`${g.provenance.bundleSha256}:${g.provenance.sourceSha256}:${node.id}:${binding}`} nodeId={node.id} name={node.name} deploymentId={binding} source={g.provenance.sourceSha256} bundle={g.provenance.bundleSha256}/>}
 {node&&tab==='Serial console'&&<section aria-label="Selected node serial console"><h3>Serial console</h3><Facts items={[["Node",node.name],["Console capability",'Not checked'],["Connection",'Disconnected']]}/><div className="wb-console-empty" role="status">{binding?'Runtime enrolled; no qualified serial-console discovery adapter is connected.':'Connect an enrolled runtime before checking serial-console availability.'}</div><button disabled>Connect serial console</button><p className="wb-help">Connect is available only when a serial console is detected for this node. A missing console will be shown as unavailable; an unchecked console is not assumed absent. A shell, native kind or open TCP port does not establish a serial console. Discovery and transport remain unqualified.</p></section>}
 {tab==='Dependencies'&&<><p className="wb-small">Partial inventory. File presence is not deployment readiness.</p>{deps.map(d=><section className="wb-interface" key={d.id}><strong>{d.label}</strong><p>{d.availability.replaceAll('_',' ')}</p></section>)}</>}
 <CaptureSettings deploymentId={binding} onInvalidated={invalidate} key={`${g.provenance.bundleSha256}:${g.provenance.sourceSha256}:${g.revision}`} link={link} visible={tab==='Capture & TShark'}/>
 {tab==='Evidence'&&<><Facts items={[["Object ID",selected??'No selection'],["Bundle",g.provenance.bundleId],["Source SHA-256",g.provenance.sourceSha256],["Bundle SHA-256",g.provenance.bundleSha256],["Native commit",g.provenance.nativeCommit],["Original execution",g.provenance.completedAt],["Evidence use",recorded?'Historical recording':'New execution']]}/><details><summary>Companion inventory</summary>{bundle?.companionInventory?.map(f=><p key={f.name}>{f.name}<small>{f.sha256}</small></p>)}</details></>}
 </aside></div><details className="wb-diagnostics" open={g.status==='rejected'}><summary>Diagnostics · {g.diagnostics.length?g.diagnostics.length+' loading notes':'no native loading errors'}</summary>{g.diagnostics.map((d,i)=><p key={i}>{d.code} · {d.stage}: {d.message}</p>)}<p>Native declarations and runtime evidence remain separate. Unchecked prerequisites are not satisfied prerequisites.</p></details></>:<section className="wb-empty"><span aria-hidden="true">◇</span><h2>Open a topology to explore your lab</h2><p>Choose an approved lab on the left. Load native declarations when a worker is available, or open an explicitly labeled recording.</p><p>Inspect nodes and exact interfaces, then connect a matching enrolled runtime—all in this workspace.</p></section>}
 </main></div></div>;
}
